// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Avg_dup_Block_entry1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stage3,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        imgBuff_out_din,
        imgBuff_out_full_n,
        imgBuff_out_write,
        Centro_dout,
        Centro_empty_n,
        Centro_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] stage3;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [15:0] imgBuff_out_din;
input   imgBuff_out_full_n;
output   imgBuff_out_write;
input  [15:0] Centro_dout;
input   Centro_empty_n;
output   Centro_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ImgBuff_in_read;
reg imgBuff_out_write;
reg Centro_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire    grp_duplicateAndCentralizeImg_fu_28_ap_start;
wire    grp_duplicateAndCentralizeImg_fu_28_ap_done;
wire    grp_duplicateAndCentralizeImg_fu_28_ap_idle;
wire    grp_duplicateAndCentralizeImg_fu_28_ap_ready;
wire    grp_duplicateAndCentralizeImg_fu_28_Centro_read;
wire    grp_duplicateAndCentralizeImg_fu_28_ImgBuff_in_read;
wire   [15:0] grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_din;
wire    grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_write;
reg    grp_duplicateAndCentralizeImg_fu_28_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_duplicateAndCentralizeImg_fu_28_ap_start_reg = 1'b0;
end

Avg_dup_duplicateAndCentralizeImg grp_duplicateAndCentralizeImg_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_duplicateAndCentralizeImg_fu_28_ap_start),
    .ap_done(grp_duplicateAndCentralizeImg_fu_28_ap_done),
    .ap_idle(grp_duplicateAndCentralizeImg_fu_28_ap_idle),
    .ap_ready(grp_duplicateAndCentralizeImg_fu_28_ap_ready),
    .Centro_dout(Centro_dout),
    .Centro_empty_n(Centro_empty_n),
    .Centro_read(grp_duplicateAndCentralizeImg_fu_28_Centro_read),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(grp_duplicateAndCentralizeImg_fu_28_ImgBuff_in_read),
    .imgBuff_out_din(grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_din),
    .imgBuff_out_full_n(imgBuff_out_full_n),
    .imgBuff_out_write(grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_duplicateAndCentralizeImg_fu_28_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call0) & (stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_duplicateAndCentralizeImg_fu_28_ap_start_reg <= 1'b1;
        end else if ((grp_duplicateAndCentralizeImg_fu_28_ap_ready == 1'b1)) begin
            grp_duplicateAndCentralizeImg_fu_28_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Centro_read = grp_duplicateAndCentralizeImg_fu_28_Centro_read;
    end else begin
        Centro_read = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ImgBuff_in_read = grp_duplicateAndCentralizeImg_fu_28_ImgBuff_in_read;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        imgBuff_out_write = grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_write;
    end else begin
        imgBuff_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_duplicateAndCentralizeImg_fu_28_ap_done == 1'b0) & (stage3 == 1'd0));
end

assign grp_duplicateAndCentralizeImg_fu_28_ap_start = grp_duplicateAndCentralizeImg_fu_28_ap_start_reg;

assign imgBuff_out_din = grp_duplicateAndCentralizeImg_fu_28_imgBuff_out_din;

endmodule //Avg_dup_Block_entry1_proc
