// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Avg_dup_duplicateAndCentralizeImg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Centro_dout,
        Centro_empty_n,
        Centro_read,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        imgBuff_out_din,
        imgBuff_out_full_n,
        imgBuff_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] Centro_dout;
input   Centro_empty_n;
output   Centro_read;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [15:0] imgBuff_out_din;
input   imgBuff_out_full_n;
output   imgBuff_out_write;

reg ap_idle;
reg Centro_read;
reg ImgBuff_in_read;
reg imgBuff_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] cmp7_reg_273;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln56_fu_129_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ImgBuff_in_blk_n;
wire    ap_block_pp0_stage0;
reg    imgBuff_out_blk_n;
reg    Centro_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln56_fu_153_p3;
reg   [4:0] select_ln56_reg_267;
wire   [0:0] cmp7_fu_175_p2;
wire   [3:0] empty_fu_206_p1;
reg   [3:0] empty_reg_277;
reg  signed [15:0] pixb_reg_287;
wire   [15:0] centroid_q1;
reg   [15:0] centroid_load_reg_294;
wire   [3:0] centroid_address0;
reg    centroid_ce0;
reg    centroid_we0;
wire   [3:0] centroid_address1;
reg    centroid_ce1;
wire   [63:0] zext_ln58_fu_202_p1;
wire   [63:0] zext_ln75_fu_209_p1;
reg   [4:0] itBand_fu_52;
wire   [4:0] add_ln81_fu_181_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_itBand_load;
reg   [6:0] itPixel_fu_56;
wire   [6:0] select_ln56_1_fu_167_p3;
reg   [6:0] ap_sig_allocacmp_itPixel_load;
reg   [10:0] indvar_flatten_fu_60;
wire   [10:0] add_ln56_fu_135_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln58_fu_147_p2;
wire   [6:0] add_ln56_1_fu_161_p2;
wire   [16:0] centroid_load_cast_fu_216_p1;
wire  signed [16:0] sext_ln75_fu_213_p1;
wire   [0:0] icmp_ln75_fu_219_p2;
wire   [15:0] sub_ln75_fu_225_p2;
wire   [15:0] sub_ln75_1_fu_229_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 itBand_fu_52 = 5'd0;
#0 itPixel_fu_56 = 7'd0;
#0 indvar_flatten_fu_60 = 11'd0;
#0 ap_done_reg = 1'b0;
end

Avg_dup_duplicateAndCentralizeImg_centroid_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
centroid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(centroid_address0),
    .ce0(centroid_ce0),
    .we0(centroid_we0),
    .d0(Centro_dout),
    .address1(centroid_address1),
    .ce1(centroid_ce1),
    .q1(centroid_q1)
);

Avg_dup_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_60 <= add_ln56_fu_135_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_60 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            itBand_fu_52 <= add_ln81_fu_181_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            itBand_fu_52 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln56_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            itPixel_fu_56 <= select_ln56_1_fu_167_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            itPixel_fu_56 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp7_reg_273 <= cmp7_fu_175_p2;
        empty_reg_277 <= empty_fu_206_p1;
        select_ln56_reg_267 <= select_ln56_fu_153_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        pixb_reg_287 <= ImgBuff_in_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        centroid_load_reg_294 <= centroid_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (cmp7_reg_273 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Centro_blk_n = Centro_empty_n;
    end else begin
        Centro_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp7_reg_273 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Centro_read = 1'b1;
    end else begin
        Centro_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ImgBuff_in_blk_n = ImgBuff_in_empty_n;
    end else begin
        ImgBuff_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ImgBuff_in_read = 1'b1;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln56_fu_129_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_itBand_load = 5'd0;
    end else begin
        ap_sig_allocacmp_itBand_load = itBand_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_itPixel_load = 7'd0;
    end else begin
        ap_sig_allocacmp_itPixel_load = itPixel_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        centroid_ce0 = 1'b1;
    end else begin
        centroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        centroid_ce1 = 1'b1;
    end else begin
        centroid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp7_reg_273 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        centroid_we0 = 1'b1;
    end else begin
        centroid_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgBuff_out_blk_n = imgBuff_out_full_n;
    end else begin
        imgBuff_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgBuff_out_write = 1'b1;
    end else begin
        imgBuff_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln56_1_fu_161_p2 = (ap_sig_allocacmp_itPixel_load + 7'd1);

assign add_ln56_fu_135_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln81_fu_181_p2 = (select_ln56_fu_153_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((cmp7_reg_273 == 1'd1) & (1'b0 == Centro_empty_n));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (1'b0 == ImgBuff_in_empty_n);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (imgBuff_out_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign centroid_address0 = zext_ln58_fu_202_p1;

assign centroid_address1 = zext_ln75_fu_209_p1;

assign centroid_load_cast_fu_216_p1 = centroid_load_reg_294;

assign cmp7_fu_175_p2 = ((select_ln56_1_fu_167_p3 == 7'd0) ? 1'b1 : 1'b0);

assign empty_fu_206_p1 = select_ln56_reg_267[3:0];

assign icmp_ln56_fu_129_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_147_p2 = ((ap_sig_allocacmp_itBand_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_219_p2 = (($signed(centroid_load_cast_fu_216_p1) < $signed(sext_ln75_fu_213_p1)) ? 1'b1 : 1'b0);

assign imgBuff_out_din = ((icmp_ln75_fu_219_p2[0:0] == 1'b1) ? sub_ln75_fu_225_p2 : sub_ln75_1_fu_229_p2);

assign select_ln56_1_fu_167_p3 = ((icmp_ln58_fu_147_p2[0:0] == 1'b1) ? add_ln56_1_fu_161_p2 : ap_sig_allocacmp_itPixel_load);

assign select_ln56_fu_153_p3 = ((icmp_ln58_fu_147_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_itBand_load);

assign sext_ln75_fu_213_p1 = pixb_reg_287;

assign sub_ln75_1_fu_229_p2 = ($signed(centroid_load_reg_294) - $signed(pixb_reg_287));

assign sub_ln75_fu_225_p2 = ($signed(pixb_reg_287) - $signed(centroid_load_reg_294));

assign zext_ln58_fu_202_p1 = select_ln56_reg_267;

assign zext_ln75_fu_209_p1 = empty_reg_277;

endmodule //Avg_dup_duplicateAndCentralizeImg
