// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module BRIGHT_brightness (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        Vector_b_din,
        Vector_b_full_n,
        Vector_b_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [31:0] Vector_b_din;
input   Vector_b_full_n;
output   Vector_b_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ImgBuff_in_read;
reg[31:0] Vector_b_din;
reg Vector_b_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Vector_b_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [47:0] trunc_ln1_reg_159;
wire   [4:0] tmp_fu_132_p3;
reg   [4:0] tmp_reg_164;
wire    ap_CS_fsm_state5;
reg   [3:0] Mem_address0;
reg    Mem_ce0;
reg    Mem_we0;
wire   [15:0] Mem_q0;
reg   [4:0] hpixel_address0;
reg    hpixel_ce0;
reg    hpixel_we0;
wire   [15:0] hpixel_q0;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_done;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_idle;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_ready;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ImgBuff_in_read;
wire   [4:0] grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_address0;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_ce0;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_we0;
wire   [15:0] grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_d0;
wire   [15:0] grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_maxIndex_1_out;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_maxIndex_1_out_ap_vld;
wire   [63:0] grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out_ap_vld;
wire   [0:0] grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_sel_pixel_buffer_1_out;
wire    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_sel_pixel_buffer_1_out_ap_vld;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_done;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_idle;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_ready;
wire   [31:0] grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_din;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_write;
wire   [4:0] grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_address0;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_ce0;
wire   [3:0] grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_address0;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_ce0;
wire    grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_we0;
wire   [15:0] grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_d0;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_idle;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_ready;
wire   [31:0] grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_din;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_write;
wire   [3:0] grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_address0;
wire    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_ce0;
reg    grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [31:0] zext_ln277_fu_100_p1;
wire   [31:0] trunc_ln278_fu_108_p1;
wire   [0:0] xor_ln280_fu_126_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg = 1'b0;
#0 grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg = 1'b0;
#0 grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg = 1'b0;
end

BRIGHT_brightness_Mem_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
Mem_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Mem_address0),
    .ce0(Mem_ce0),
    .we0(Mem_we0),
    .d0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_d0),
    .q0(Mem_q0)
);

BRIGHT_brightness_hpixel_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
hpixel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hpixel_address0),
    .ce0(hpixel_ce0),
    .we0(hpixel_we0),
    .d0(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_d0),
    .q0(hpixel_q0)
);

BRIGHT_brightness_Pipeline_brig_p_loop_sum_b_loop grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start),
    .ap_done(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_done),
    .ap_idle(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_idle),
    .ap_ready(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_ready),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ImgBuff_in_read),
    .hpixel_address0(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_address0),
    .hpixel_ce0(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_ce0),
    .hpixel_we0(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_we0),
    .hpixel_d0(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_d0),
    .maxIndex_1_out(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_maxIndex_1_out),
    .maxIndex_1_out_ap_vld(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_maxIndex_1_out_ap_vld),
    .actualMaxBrightness_1_out(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out),
    .actualMaxBrightness_1_out_ap_vld(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out_ap_vld),
    .sel_pixel_buffer_1_out(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_sel_pixel_buffer_1_out),
    .sel_pixel_buffer_1_out_ap_vld(grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_sel_pixel_buffer_1_out_ap_vld)
);

BRIGHT_brightness_Pipeline_quVectors_b_PES grp_brightness_Pipeline_quVectors_b_PES_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start),
    .ap_done(grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_done),
    .ap_idle(grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_idle),
    .ap_ready(grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_ready),
    .Vector_b_din(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_din),
    .Vector_b_full_n(Vector_b_full_n),
    .Vector_b_write(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_write),
    .zext_ln209(tmp_reg_164),
    .hpixel_address0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_address0),
    .hpixel_ce0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_ce0),
    .hpixel_q0(hpixel_q0),
    .Mem_address0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_address0),
    .Mem_ce0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_ce0),
    .Mem_we0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_we0),
    .Mem_d0(grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_d0)
);

BRIGHT_brightness_Pipeline_VITIS_LOOP_226_1 grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start),
    .ap_done(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done),
    .ap_idle(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_idle),
    .ap_ready(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_ready),
    .Vector_b_din(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_din),
    .Vector_b_full_n(Vector_b_full_n),
    .Vector_b_write(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_write),
    .Mem_address0(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_address0),
    .Mem_ce0(grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_ce0),
    .Mem_q0(Mem_q0),
    .trunc_ln1(trunc_ln1_reg_159)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_ready == 1'b1)) begin
            grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg <= 1'b1;
        end else if ((grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_ready == 1'b1)) begin
            grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_ready == 1'b1)) begin
            grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_reg_164[4] <= tmp_fu_132_p3[4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln1_reg_159 <= {{grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out[63:16]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ImgBuff_in_read = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ImgBuff_in_read;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Mem_address0 = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Mem_address0 = grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_address0;
    end else begin
        Mem_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Mem_ce0 = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Mem_ce0 = grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_ce0;
    end else begin
        Mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Mem_we0 = grp_brightness_Pipeline_quVectors_b_PES_fu_80_Mem_we0;
    end else begin
        Mem_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        Vector_b_blk_n = Vector_b_full_n;
    end else begin
        Vector_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == Vector_b_full_n))) begin
        Vector_b_din = trunc_ln278_fu_108_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == Vector_b_full_n))) begin
        Vector_b_din = zext_ln277_fu_100_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        Vector_b_din = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_din;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Vector_b_din = grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_din;
    end else begin
        Vector_b_din = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_din;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (1'b1 == Vector_b_full_n)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == Vector_b_full_n)))) begin
        Vector_b_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        Vector_b_write = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_Vector_b_write;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Vector_b_write = grp_brightness_Pipeline_quVectors_b_PES_fu_80_Vector_b_write;
    end else begin
        Vector_b_write = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Vector_b_full_n)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Vector_b_full_n)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state9) & (grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        hpixel_address0 = grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hpixel_address0 = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_address0;
    end else begin
        hpixel_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        hpixel_ce0 = grp_brightness_Pipeline_quVectors_b_PES_fu_80_hpixel_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hpixel_ce0 = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_ce0;
    end else begin
        hpixel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hpixel_we0 = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_hpixel_we0;
    end else begin
        hpixel_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == Vector_b_full_n))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == Vector_b_full_n))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start = grp_brightness_Pipeline_VITIS_LOOP_226_1_fu_89_ap_start_reg;

assign grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_ap_start_reg;

assign grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start = grp_brightness_Pipeline_quVectors_b_PES_fu_80_ap_start_reg;

assign tmp_fu_132_p3 = {{xor_ln280_fu_126_p2}, {4'd0}};

assign trunc_ln278_fu_108_p1 = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_actualMaxBrightness_1_out[31:0];

assign xor_ln280_fu_126_p2 = (grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_sel_pixel_buffer_1_out ^ 1'd1);

assign zext_ln277_fu_100_p1 = grp_brightness_Pipeline_brig_p_loop_sum_b_loop_fu_67_maxIndex_1_out;

always @ (posedge ap_clk) begin
    tmp_reg_164[3:0] <= 4'b0000;
end

endmodule //BRIGHT_brightness
