// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="BRIGHT_BRIGHT,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.848000,HLS_SYN_LAT=1009,HLS_SYN_TPT=1010,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5392,HLS_SYN_LUT=4864,HLS_VERSION=2023_2}" *)

module BRIGHT (
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        Vector_b_din,
        Vector_b_full_n,
        Vector_b_write,
        stage3,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);

////////////////////////////////////
//always_ff @(posedge ap_clk or negedge ap_rst) begin
//    if (ap_rst) begin
//        $display("Reset inside BRIGHT");
//    end
//end
////////////////////////////////////

input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [31:0] Vector_b_din;
input   Vector_b_full_n;
output   Vector_b_write;
input  [0:0] stage3;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire    Block_entry1_proc_U0_ImgBuff_in_read;
wire   [31:0] Block_entry1_proc_U0_Vector_b_din;
wire    Block_entry1_proc_U0_Vector_b_write;

BRIGHT_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .stage3(stage3),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(Block_entry1_proc_U0_ImgBuff_in_read),
    .Vector_b_din(Block_entry1_proc_U0_Vector_b_din),
    .Vector_b_full_n(Vector_b_full_n),
    .Vector_b_write(Block_entry1_proc_U0_Vector_b_write)
);

assign Block_entry1_proc_U0_ap_continue = 1'b1;

assign Block_entry1_proc_U0_ap_start = ap_start;

assign ImgBuff_in_read = Block_entry1_proc_U0_ImgBuff_in_read;

assign Vector_b_din = Block_entry1_proc_U0_Vector_b_din;

assign Vector_b_write = Block_entry1_proc_U0_Vector_b_write;

assign ap_done = Block_entry1_proc_U0_ap_done;

assign ap_idle = Block_entry1_proc_U0_ap_idle;

assign ap_ready = Block_entry1_proc_U0_ap_ready;

endmodule //BRIGHT
