// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module BRIGHT_brightness_Pipeline_brig_p_loop_sum_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        hpixel_address0,
        hpixel_ce0,
        hpixel_we0,
        hpixel_d0,
        maxIndex_1_out,
        maxIndex_1_out_ap_vld,
        actualMaxBrightness_1_out,
        actualMaxBrightness_1_out_ap_vld,
        sel_pixel_buffer_1_out,
        sel_pixel_buffer_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [4:0] hpixel_address0;
output   hpixel_ce0;
output   hpixel_we0;
output  [15:0] hpixel_d0;
output  [15:0] maxIndex_1_out;
output   maxIndex_1_out_ap_vld;
output  [63:0] actualMaxBrightness_1_out;
output   actualMaxBrightness_1_out_ap_vld;
output  [0:0] sel_pixel_buffer_1_out;
output   sel_pixel_buffer_1_out_ap_vld;

reg ap_idle;
reg ImgBuff_in_read;
reg hpixel_ce0;
reg hpixel_we0;
reg maxIndex_1_out_ap_vld;
reg actualMaxBrightness_1_out_ap_vld;
reg sel_pixel_buffer_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln257_reg_479;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln257_fu_167_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [63:0] brightness_calc_unsigned_short_unsigned_char_short_short_16_ap_uint_unsig;
reg    ImgBuff_in_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] sel_pixel_buffer_1_reg_136;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln257_reg_479_pp0_iter1_reg;
reg  signed [15:0] pixb_reg_483;
wire   [0:0] sel_pixel_buffer_fu_386_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_init;
wire   [63:0] zext_ln178_fu_288_p1;
wire   [63:0] actualBrightness_fu_324_p3;
reg   [63:0] actualMaxBrightness_1_fu_76;
wire   [63:0] actualMaxBrightness_fu_394_p3;
reg   [15:0] maxIndex_1_fu_80;
wire   [15:0] maxIndex_fu_402_p3;
reg   [4:0] itBand_fu_84;
wire   [4:0] add_ln259_fu_410_p2;
reg   [6:0] itPixel_fu_88;
wire   [6:0] select_ln257_fu_216_p3;
reg   [10:0] indvar_flatten_fu_92;
wire   [10:0] add_ln257_fu_173_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln259_fu_202_p2;
wire   [6:0] itPixel_2_fu_196_p2;
wire   [4:0] select_ln248_fu_208_p3;
wire   [0:0] cmp_i_fu_228_p2;
wire   [0:0] icmp_ln172_fu_234_p2;
wire   [0:0] and_ln172_fu_240_p2;
wire   [0:0] xor_ln172_fu_246_p2;
wire   [0:0] sel_pixel_buffer_2_fu_252_p2;
wire   [4:0] tmp_1_fu_274_p3;
wire   [4:0] add_ln178_fu_282_p2;
wire  signed [15:0] mul_ln184_fu_296_p0;
wire  signed [31:0] sext_ln184_fu_293_p1;
wire  signed [15:0] mul_ln184_fu_296_p1;
wire   [31:0] mul_ln184_fu_296_p2;
wire   [43:0] tmp_2_fu_302_p3;
wire  signed [63:0] sext_ln184_1_fu_310_p1;
wire   [63:0] add_ln184_fu_318_p2;
wire   [63:0] actualMaxBrightness_2_fu_258_p3;
wire   [0:0] xor_ln193_fu_350_p2;
wire   [0:0] icmp_ln191_fu_344_p2;
wire   [0:0] sel_pixel_buffer_3_fu_356_p2;
wire   [15:0] itPixel_assign_fu_224_p1;
wire   [15:0] maxIndex_2_fu_266_p3;
wire   [0:0] icmp_ln187_fu_338_p2;
wire   [0:0] sel_pixel_buffer_4_fu_362_p3;
wire   [63:0] actualMaxBrightness_4_fu_370_p3;
wire   [15:0] maxIndex_3_fu_378_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 brightness_calc_unsigned_short_unsigned_char_short_short_16_ap_uint_unsig = 64'd0;
#0 actualMaxBrightness_1_fu_76 = 64'd0;
#0 maxIndex_1_fu_80 = 16'd0;
#0 itBand_fu_84 = 5'd0;
#0 itPixel_fu_88 = 7'd0;
#0 indvar_flatten_fu_92 = 11'd0;
#0 ap_done_reg = 1'b0;
end

BRIGHT_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(mul_ln184_fu_296_p0),
    .din1(mul_ln184_fu_296_p1),
    .dout(mul_ln184_fu_296_p2)
);

BRIGHT_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln257_fu_167_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_92 <= add_ln257_fu_173_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_92 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            itBand_fu_84 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln257_reg_479_pp0_iter1_reg == 1'd0))) begin
            itBand_fu_84 <= add_ln259_fu_410_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            itPixel_fu_88 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln257_reg_479_pp0_iter1_reg == 1'd0))) begin
            itPixel_fu_88 <= select_ln257_fu_216_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln257_reg_479_pp0_iter1_reg == 1'd0))) begin
        sel_pixel_buffer_1_reg_136 <= sel_pixel_buffer_fu_386_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        sel_pixel_buffer_1_reg_136 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln257_reg_479_pp0_iter1_reg == 1'd0))) begin
        actualMaxBrightness_1_fu_76 <= actualMaxBrightness_fu_394_p3;
        brightness_calc_unsigned_short_unsigned_char_short_short_16_ap_uint_unsig <= actualBrightness_fu_324_p3;
        maxIndex_1_fu_80 <= maxIndex_fu_402_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln257_reg_479 <= icmp_ln257_fu_167_p2;
        icmp_ln257_reg_479_pp0_iter1_reg <= icmp_ln257_reg_479;
        pixb_reg_483 <= ImgBuff_in_dout;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln257_reg_479 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgBuff_in_blk_n = ImgBuff_in_empty_n;
    end else begin
        ImgBuff_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln257_reg_479 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgBuff_in_read = 1'b1;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln257_reg_479 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        actualMaxBrightness_1_out_ap_vld = 1'b1;
    end else begin
        actualMaxBrightness_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln257_fu_167_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln257_reg_479 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        hpixel_ce0 = 1'b1;
    end else begin
        hpixel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln257_reg_479_pp0_iter1_reg == 1'd0))) begin
        hpixel_we0 = 1'b1;
    end else begin
        hpixel_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln257_reg_479 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        maxIndex_1_out_ap_vld = 1'b1;
    end else begin
        maxIndex_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln257_reg_479 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sel_pixel_buffer_1_out_ap_vld = 1'b1;
    end else begin
        sel_pixel_buffer_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign actualBrightness_fu_324_p3 = ((icmp_ln172_fu_234_p2[0:0] == 1'b1) ? sext_ln184_1_fu_310_p1 : add_ln184_fu_318_p2);

assign actualMaxBrightness_1_out = actualMaxBrightness_1_fu_76;

assign actualMaxBrightness_2_fu_258_p3 = ((and_ln172_fu_240_p2[0:0] == 1'b1) ? 64'd0 : actualMaxBrightness_1_fu_76);

assign actualMaxBrightness_4_fu_370_p3 = ((icmp_ln191_fu_344_p2[0:0] == 1'b1) ? actualBrightness_fu_324_p3 : actualMaxBrightness_2_fu_258_p3);

assign actualMaxBrightness_fu_394_p3 = ((icmp_ln187_fu_338_p2[0:0] == 1'b1) ? actualMaxBrightness_4_fu_370_p3 : actualMaxBrightness_2_fu_258_p3);

assign add_ln178_fu_282_p2 = (tmp_1_fu_274_p3 + select_ln248_fu_208_p3);

assign add_ln184_fu_318_p2 = ($signed(brightness_calc_unsigned_short_unsigned_char_short_short_16_ap_uint_unsig) + $signed(sext_ln184_1_fu_310_p1));

assign add_ln257_fu_173_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln259_fu_410_p2 = (select_ln248_fu_208_p3 + 5'd1);

assign and_ln172_fu_240_p2 = (icmp_ln172_fu_234_p2 & cmp_i_fu_228_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln257_reg_479 == 1'd0) & (1'b0 == ImgBuff_in_empty_n));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp_i_fu_228_p2 = ((select_ln257_fu_216_p3 == 7'd0) ? 1'b1 : 1'b0);

assign hpixel_address0 = zext_ln178_fu_288_p1;

assign hpixel_d0 = pixb_reg_483;

assign icmp_ln172_fu_234_p2 = ((select_ln248_fu_208_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_338_p2 = ((select_ln248_fu_208_p3 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_344_p2 = (($signed(actualBrightness_fu_324_p3) > $signed(actualMaxBrightness_2_fu_258_p3)) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_167_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln259_fu_202_p2 = ((itBand_fu_84 == 5'd16) ? 1'b1 : 1'b0);

assign itPixel_2_fu_196_p2 = (itPixel_fu_88 + 7'd1);

assign itPixel_assign_fu_224_p1 = select_ln257_fu_216_p3;

assign maxIndex_1_out = maxIndex_1_fu_80;

assign maxIndex_2_fu_266_p3 = ((and_ln172_fu_240_p2[0:0] == 1'b1) ? 16'd0 : maxIndex_1_fu_80);

assign maxIndex_3_fu_378_p3 = ((icmp_ln191_fu_344_p2[0:0] == 1'b1) ? itPixel_assign_fu_224_p1 : maxIndex_2_fu_266_p3);

assign maxIndex_fu_402_p3 = ((icmp_ln187_fu_338_p2[0:0] == 1'b1) ? maxIndex_3_fu_378_p3 : maxIndex_2_fu_266_p3);

assign mul_ln184_fu_296_p0 = sext_ln184_fu_293_p1;

assign mul_ln184_fu_296_p1 = sext_ln184_fu_293_p1;

assign sel_pixel_buffer_1_out = sel_pixel_buffer_1_reg_136;

assign sel_pixel_buffer_2_fu_252_p2 = (xor_ln172_fu_246_p2 & sel_pixel_buffer_1_reg_136);

assign sel_pixel_buffer_3_fu_356_p2 = (xor_ln193_fu_350_p2 | and_ln172_fu_240_p2);

assign sel_pixel_buffer_4_fu_362_p3 = ((icmp_ln191_fu_344_p2[0:0] == 1'b1) ? sel_pixel_buffer_3_fu_356_p2 : sel_pixel_buffer_2_fu_252_p2);

assign sel_pixel_buffer_fu_386_p3 = ((icmp_ln187_fu_338_p2[0:0] == 1'b1) ? sel_pixel_buffer_4_fu_362_p3 : sel_pixel_buffer_2_fu_252_p2);

assign select_ln248_fu_208_p3 = ((icmp_ln259_fu_202_p2[0:0] == 1'b1) ? 5'd0 : itBand_fu_84);

assign select_ln257_fu_216_p3 = ((icmp_ln259_fu_202_p2[0:0] == 1'b1) ? itPixel_2_fu_196_p2 : itPixel_fu_88);

assign sext_ln184_1_fu_310_p1 = $signed(tmp_2_fu_302_p3);

assign sext_ln184_fu_293_p1 = pixb_reg_483;

assign tmp_1_fu_274_p3 = {{sel_pixel_buffer_2_fu_252_p2}, {4'd0}};

assign tmp_2_fu_302_p3 = {{mul_ln184_fu_296_p2}, {12'd0}};

assign xor_ln172_fu_246_p2 = (1'd1 ^ and_ln172_fu_240_p2);

assign xor_ln193_fu_350_p2 = (sel_pixel_buffer_1_reg_136 ^ 1'd1);

assign zext_ln178_fu_288_p1 = add_ln178_fu_282_p2;

endmodule //BRIGHT_brightness_Pipeline_brig_p_loop_sum_b_loop
