// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module PROJECTION_cpy_xVectors (
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        xVector_dst_address0,
        xVector_dst_ce0,
        xVector_dst_d0,
        xVector_dst_q0,
        xVector_dst_we0,
        xVector_dst_address1,
        xVector_dst_ce1,
        xVector_dst_d1,
        xVector_dst_q1,
        xVector_dst_we1,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [3:0] xVector_dst_address0;
output   xVector_dst_ce0;
output  [31:0] xVector_dst_d0;
input  [31:0] xVector_dst_q0;
output   xVector_dst_we0;
output  [3:0] xVector_dst_address1;
output   xVector_dst_ce1;
output  [31:0] xVector_dst_d1;
input  [31:0] xVector_dst_q1;
output   xVector_dst_we1;
output  [31:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_start;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_done;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_continue;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_idle;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_ready;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_in_Buffer_img_read;
wire   [31:0] cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_din;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_write;
wire   [3:0] cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_address0;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_ce0;
wire    cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_we0;
wire   [31:0] cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_d0;

PROJECTION_cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1 cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_start),
    .ap_done(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_done),
    .ap_continue(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_continue),
    .ap_idle(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_idle),
    .ap_ready(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_ready),
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_in_Buffer_img_read),
    .out_Buffer_img_din(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_din),
    .out_Buffer_img_full_n(out_Buffer_img_full_n),
    .out_Buffer_img_write(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_write),
    .xVector_dst_address0(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_address0),
    .xVector_dst_ce0(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_ce0),
    .xVector_dst_we0(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_we0),
    .xVector_dst_d0(cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_d0)
);

assign ap_done = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_done;

assign ap_idle = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_idle;

assign ap_ready = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_ready;

assign cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_continue = ap_continue;

assign cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_ap_start = ap_start;

assign in_Buffer_img_read = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_in_Buffer_img_read;

assign out_Buffer_img_din = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_din;

assign out_Buffer_img_write = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_out_Buffer_img_write;

assign xVector_dst_address0 = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_address0;

assign xVector_dst_address1 = 4'd0;

assign xVector_dst_ce0 = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_ce0;

assign xVector_dst_ce1 = 1'b0;

assign xVector_dst_d0 = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_d0;

assign xVector_dst_d1 = 32'd0;

assign xVector_dst_we0 = cpy_xVectors_Loop_VITIS_LOOP_122_1_proc1_U0_xVector_dst_we0;

assign xVector_dst_we1 = 1'b0;

endmodule //PROJECTION_cpy_xVectors
