// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module PROJECTION_projecting_Pipeline_proj_p_loop_proj_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        Buffer_Proj_din,
        Buffer_Proj_full_n,
        Buffer_Proj_write,
        out_projection_din,
        out_projection_full_n,
        out_projection_write,
        p_uVector_address0,
        p_uVector_ce0,
        p_uVector_q0,
        zext_ln175
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [31:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
output  [31:0] Buffer_Proj_din;
input   Buffer_Proj_full_n;
output   Buffer_Proj_write;
output  [15:0] out_projection_din;
input   out_projection_full_n;
output   out_projection_write;
output  [3:0] p_uVector_address0;
output   p_uVector_ce0;
input  [31:0] p_uVector_q0;
input  [15:0] zext_ln175;

reg ap_idle;
reg in_Buffer_img_read;
reg out_Buffer_img_write;
reg Buffer_Proj_write;
reg out_projection_write;
reg p_uVector_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln165_reg_329;
reg   [0:0] icmp_ln165_reg_329_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln189_fu_154_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [63:0] projectionValueLong_pe_0;
reg    in_Buffer_img_blk_n;
wire    ap_block_pp0_stage0;
reg    out_Buffer_img_blk_n;
reg    Buffer_Proj_blk_n;
reg    out_projection_blk_n;
wire   [43:0] zext_ln175_cast_fu_137_p1;
reg   [43:0] zext_ln175_cast_reg_305;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln189_fu_180_p3;
reg   [4:0] select_ln189_reg_314;
wire   [15:0] pixb_fu_193_p1;
reg  signed [15:0] pixb_reg_319;
wire   [0:0] icmp_ln165_fu_197_p2;
reg  signed [31:0] pprojection_reg_333;
wire   [63:0] zext_ln191_fu_188_p1;
wire   [63:0] projectionValueLong_fu_242_p3;
reg   [4:0] itBand_fu_74;
wire   [4:0] add_ln191_fu_203_p2;
wire    ap_loop_init;
reg   [10:0] indvar_flatten_fu_78;
wire   [10:0] add_ln189_fu_160_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] mul_ln175_fu_133_p1;
wire   [0:0] icmp_ln191_fu_174_p2;
wire   [47:0] mul_ln161_fu_129_p2;
wire  signed [63:0] sext_ln161_1_fu_228_p1;
wire   [0:0] cmp_i_i_fu_214_p2;
wire   [63:0] add_ln161_fu_236_p2;
wire  signed [32:0] sext_ln173_fu_266_p1;
wire  signed [32:0] positiveProjectionLong_fu_269_p2;
wire   [43:0] mul_ln175_fu_133_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 projectionValueLong_pe_0 = 64'd0;
#0 itBand_fu_74 = 5'd0;
#0 indvar_flatten_fu_78 = 11'd0;
#0 ap_done_reg = 1'b0;
end

PROJECTION_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U7(
    .din0(p_uVector_q0),
    .din1(pixb_reg_319),
    .dout(mul_ln161_fu_129_p2)
);

PROJECTION_mul_33s_16ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 44 ))
mul_33s_16ns_44_1_1_U8(
    .din0(positiveProjectionLong_fu_269_p2),
    .din1(mul_ln175_fu_133_p1),
    .dout(mul_ln175_fu_133_p2)
);

PROJECTION_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln189_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_78 <= add_ln189_fu_160_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_78 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            itBand_fu_74 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            itBand_fu_74 <= add_ln191_fu_203_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln165_reg_329 <= icmp_ln165_fu_197_p2;
        pixb_reg_319 <= pixb_fu_193_p1;
        select_ln189_reg_314 <= select_ln189_fu_180_p3;
        zext_ln175_cast_reg_305[15 : 0] <= zext_ln175_cast_fu_137_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln165_reg_329_pp0_iter2_reg <= icmp_ln165_reg_329;
        pprojection_reg_333 <= {{projectionValueLong_fu_242_p3[35:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        projectionValueLong_pe_0 <= projectionValueLong_fu_242_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln165_reg_329_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Buffer_Proj_blk_n = Buffer_Proj_full_n;
    end else begin
        Buffer_Proj_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln165_reg_329_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Buffer_Proj_write = 1'b1;
    end else begin
        Buffer_Proj_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln189_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_Buffer_img_blk_n = in_Buffer_img_empty_n;
    end else begin
        in_Buffer_img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_Buffer_img_read = 1'b1;
    end else begin
        in_Buffer_img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_Buffer_img_blk_n = out_Buffer_img_full_n;
    end else begin
        out_Buffer_img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_Buffer_img_write = 1'b1;
    end else begin
        out_Buffer_img_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln165_reg_329_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_projection_blk_n = out_projection_full_n;
    end else begin
        out_projection_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln165_reg_329_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_projection_write = 1'b1;
    end else begin
        out_projection_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_uVector_ce0 = 1'b1;
    end else begin
        p_uVector_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Buffer_Proj_din = pprojection_reg_333;

assign add_ln161_fu_236_p2 = ($signed(projectionValueLong_pe_0) + $signed(sext_ln161_1_fu_228_p1));

assign add_ln189_fu_160_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln191_fu_203_p2 = (select_ln189_fu_180_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((out_Buffer_img_full_n == 1'b0) | (in_Buffer_img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (((out_projection_full_n == 1'b0) & (icmp_ln165_reg_329_pp0_iter2_reg == 1'd1)) | ((icmp_ln165_reg_329_pp0_iter2_reg == 1'd1) & (1'b0 == Buffer_Proj_full_n)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp_i_i_fu_214_p2 = ((select_ln189_reg_314 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln165_fu_197_p2 = ((select_ln189_fu_180_p3 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_154_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_174_p2 = ((itBand_fu_74 == 5'd16) ? 1'b1 : 1'b0);

assign mul_ln175_fu_133_p1 = zext_ln175_cast_reg_305;

assign out_Buffer_img_din = in_Buffer_img_dout;

assign out_projection_din = {{mul_ln175_fu_133_p2[43:28]}};

assign p_uVector_address0 = zext_ln191_fu_188_p1;

assign pixb_fu_193_p1 = in_Buffer_img_dout[15:0];

assign positiveProjectionLong_fu_269_p2 = ($signed(sext_ln173_fu_266_p1) + $signed(33'd268435456));

assign projectionValueLong_fu_242_p3 = ((cmp_i_i_fu_214_p2[0:0] == 1'b1) ? sext_ln161_1_fu_228_p1 : add_ln161_fu_236_p2);

assign select_ln189_fu_180_p3 = ((icmp_ln191_fu_174_p2[0:0] == 1'b1) ? 5'd0 : itBand_fu_74);

assign sext_ln161_1_fu_228_p1 = $signed(mul_ln161_fu_129_p2);

assign sext_ln173_fu_266_p1 = pprojection_reg_333;

assign zext_ln175_cast_fu_137_p1 = zext_ln175;

assign zext_ln191_fu_188_p1 = select_ln189_fu_180_p3;

always @ (posedge ap_clk) begin
    zext_ln175_cast_reg_305[43:16] <= 28'b0000000000000000000000000000;
end

endmodule //PROJECTION_projecting_Pipeline_proj_p_loop_proj_b_loop
