// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PROJECTION_PROJECTION,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.860000,HLS_SYN_LAT=982,HLS_SYN_TPT=983,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=275,HLS_SYN_LUT=840,HLS_VERSION=2023_2}" *)

module PROJECTION (
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        Buffer_Proj_din,
        Buffer_Proj_full_n,
        Buffer_Proj_write,
        out_projection_din,
        out_projection_full_n,
        out_projection_write,
        DRPROXECTIONS,
        stage3,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [31:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
output  [31:0] Buffer_Proj_din;
input   Buffer_Proj_full_n;
output   Buffer_Proj_write;
output  [15:0] out_projection_din;
input   out_projection_full_n;
output   out_projection_write;
input  [31:0] DRPROXECTIONS;
input  [0:0] stage3;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire    Block_entry1_proc_U0_in_Buffer_img_read;
wire   [31:0] Block_entry1_proc_U0_out_Buffer_img_din;
wire    Block_entry1_proc_U0_out_Buffer_img_write;
wire   [31:0] Block_entry1_proc_U0_Buffer_Proj_din;
wire    Block_entry1_proc_U0_Buffer_Proj_write;
wire   [15:0] Block_entry1_proc_U0_out_projection_din;
wire    Block_entry1_proc_U0_out_projection_write;

PROJECTION_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .stage3(stage3),
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(Block_entry1_proc_U0_in_Buffer_img_read),
    .out_Buffer_img_din(Block_entry1_proc_U0_out_Buffer_img_din),
    .out_Buffer_img_full_n(out_Buffer_img_full_n),
    .out_Buffer_img_write(Block_entry1_proc_U0_out_Buffer_img_write),
    .Buffer_Proj_din(Block_entry1_proc_U0_Buffer_Proj_din),
    .Buffer_Proj_full_n(Buffer_Proj_full_n),
    .Buffer_Proj_write(Block_entry1_proc_U0_Buffer_Proj_write),
    .out_projection_din(Block_entry1_proc_U0_out_projection_din),
    .out_projection_full_n(out_projection_full_n),
    .out_projection_write(Block_entry1_proc_U0_out_projection_write),
    .DRPROXECTIONS(DRPROXECTIONS)
);

assign Block_entry1_proc_U0_ap_continue = 1'b1;

assign Block_entry1_proc_U0_ap_start = ap_start;

assign Buffer_Proj_din = Block_entry1_proc_U0_Buffer_Proj_din;

assign Buffer_Proj_write = Block_entry1_proc_U0_Buffer_Proj_write;

assign ap_done = Block_entry1_proc_U0_ap_done;

assign ap_idle = Block_entry1_proc_U0_ap_idle;

assign ap_ready = Block_entry1_proc_U0_ap_ready;

assign in_Buffer_img_read = Block_entry1_proc_U0_in_Buffer_img_read;

assign out_Buffer_img_din = Block_entry1_proc_U0_out_Buffer_img_din;

assign out_Buffer_img_write = Block_entry1_proc_U0_out_Buffer_img_write;

assign out_projection_din = Block_entry1_proc_U0_out_projection_din;

assign out_projection_write = Block_entry1_proc_U0_out_projection_write;

endmodule //PROJECTION
