// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module PROJECTION_Block_entry1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stage3,
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        Buffer_Proj_din,
        Buffer_Proj_full_n,
        Buffer_Proj_write,
        out_projection_din,
        out_projection_full_n,
        out_projection_write,
        DRPROXECTIONS
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] stage3;
input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [31:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
output  [31:0] Buffer_Proj_din;
input   Buffer_Proj_full_n;
output   Buffer_Proj_write;
output  [15:0] out_projection_din;
input   out_projection_full_n;
output   out_projection_write;
input  [31:0] DRPROXECTIONS;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_Buffer_img_read;
reg out_Buffer_img_write;
reg Buffer_Proj_write;
reg out_projection_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire    grp_projecting_fu_42_ap_start;
wire    grp_projecting_fu_42_ap_done;
wire    grp_projecting_fu_42_ap_idle;
wire    grp_projecting_fu_42_ap_ready;
wire    grp_projecting_fu_42_in_Buffer_img_read;
wire   [31:0] grp_projecting_fu_42_out_Buffer_img_din;
wire    grp_projecting_fu_42_out_Buffer_img_write;
wire   [31:0] grp_projecting_fu_42_Buffer_Proj_din;
wire    grp_projecting_fu_42_Buffer_Proj_write;
wire   [15:0] grp_projecting_fu_42_out_projection_din;
wire    grp_projecting_fu_42_out_projection_write;
reg    grp_projecting_fu_42_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_projecting_fu_42_ap_start_reg = 1'b0;
end

PROJECTION_projecting grp_projecting_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_projecting_fu_42_ap_start),
    .ap_done(grp_projecting_fu_42_ap_done),
    .ap_idle(grp_projecting_fu_42_ap_idle),
    .ap_ready(grp_projecting_fu_42_ap_ready),
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(grp_projecting_fu_42_in_Buffer_img_read),
    .out_Buffer_img_din(grp_projecting_fu_42_out_Buffer_img_din),
    .out_Buffer_img_full_n(out_Buffer_img_full_n),
    .out_Buffer_img_write(grp_projecting_fu_42_out_Buffer_img_write),
    .Buffer_Proj_din(grp_projecting_fu_42_Buffer_Proj_din),
    .Buffer_Proj_full_n(Buffer_Proj_full_n),
    .Buffer_Proj_write(grp_projecting_fu_42_Buffer_Proj_write),
    .out_projection_din(grp_projecting_fu_42_out_projection_din),
    .out_projection_full_n(out_projection_full_n),
    .out_projection_write(grp_projecting_fu_42_out_projection_write),
    .DRPROXECTIONS(DRPROXECTIONS)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_projecting_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if (((stage3 == 1'd0) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_projecting_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_projecting_fu_42_ap_ready == 1'b1)) begin
            grp_projecting_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Buffer_Proj_write = grp_projecting_fu_42_Buffer_Proj_write;
    end else begin
        Buffer_Proj_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_Buffer_img_read = grp_projecting_fu_42_in_Buffer_img_read;
    end else begin
        in_Buffer_img_read = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_Buffer_img_write = grp_projecting_fu_42_out_Buffer_img_write;
    end else begin
        out_Buffer_img_write = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_projection_write = grp_projecting_fu_42_out_projection_write;
    end else begin
        out_projection_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Buffer_Proj_din = grp_projecting_fu_42_Buffer_Proj_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_projecting_fu_42_ap_done == 1'b0) & (stage3 == 1'd0));
end

assign grp_projecting_fu_42_ap_start = grp_projecting_fu_42_ap_start_reg;

assign out_Buffer_img_din = grp_projecting_fu_42_out_Buffer_img_din;

assign out_projection_din = grp_projecting_fu_42_out_projection_din;

endmodule //PROJECTION_Block_entry1_proc
