// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module PROJECTION_projecting (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        Buffer_Proj_din,
        Buffer_Proj_full_n,
        Buffer_Proj_write,
        out_projection_din,
        out_projection_full_n,
        out_projection_write,
        DRPROXECTIONS
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [31:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
output  [31:0] Buffer_Proj_din;
input   Buffer_Proj_full_n;
output   Buffer_Proj_write;
output  [15:0] out_projection_din;
input   out_projection_full_n;
output   out_projection_write;
input  [31:0] DRPROXECTIONS;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_Buffer_img_read;
reg[31:0] out_Buffer_img_din;
reg out_Buffer_img_write;
reg Buffer_Proj_write;
reg out_projection_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] empty_fu_84_p1;
reg   [15:0] empty_reg_94;
wire    ap_CS_fsm_state2;
wire   [15:0] projectionScalingFactor_fu_88_p2;
reg   [15:0] projectionScalingFactor_reg_99;
wire    ap_CS_fsm_state3;
reg   [3:0] p_uVector_address0;
reg    p_uVector_ce0;
reg    p_uVector_we0;
wire   [31:0] p_uVector_q0;
wire    grp_cpy_xVectors_fu_46_in_Buffer_img_read;
wire   [3:0] grp_cpy_xVectors_fu_46_xVector_dst_address0;
wire    grp_cpy_xVectors_fu_46_xVector_dst_ce0;
wire   [31:0] grp_cpy_xVectors_fu_46_xVector_dst_d0;
wire    grp_cpy_xVectors_fu_46_xVector_dst_we0;
wire   [3:0] grp_cpy_xVectors_fu_46_xVector_dst_address1;
wire    grp_cpy_xVectors_fu_46_xVector_dst_ce1;
wire   [31:0] grp_cpy_xVectors_fu_46_xVector_dst_d1;
wire    grp_cpy_xVectors_fu_46_xVector_dst_we1;
wire   [31:0] grp_cpy_xVectors_fu_46_out_Buffer_img_din;
wire    grp_cpy_xVectors_fu_46_out_Buffer_img_write;
wire    grp_cpy_xVectors_fu_46_ap_start;
wire    grp_cpy_xVectors_fu_46_ap_done;
wire    grp_cpy_xVectors_fu_46_ap_ready;
wire    grp_cpy_xVectors_fu_46_ap_idle;
reg    grp_cpy_xVectors_fu_46_ap_continue;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_idle;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_ready;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_in_Buffer_img_read;
wire   [31:0] grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_din;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_write;
wire   [31:0] grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_din;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_write;
wire   [15:0] grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_din;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_write;
wire   [3:0] grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_address0;
wire    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_ce0;
reg    grp_cpy_xVectors_fu_46_ap_start_reg;
wire    ap_sync_grp_cpy_xVectors_fu_46_ap_ready;
wire    ap_sync_grp_cpy_xVectors_fu_46_ap_done;
reg    ap_block_state2_on_subcall_done;
reg    ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready;
reg    ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done;
reg    grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [31:0] sub_i_i_fu_72_p2;
wire   [31:0] shl_i_i_fu_78_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_cpy_xVectors_fu_46_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready = 1'b0;
#0 ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done = 1'b0;
#0 grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg = 1'b0;
end

PROJECTION_projecting_p_uVector_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_uVector_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_uVector_address0),
    .ce0(p_uVector_ce0),
    .we0(p_uVector_we0),
    .d0(grp_cpy_xVectors_fu_46_xVector_dst_d0),
    .q0(p_uVector_q0)
);

PROJECTION_cpy_xVectors grp_cpy_xVectors_fu_46(
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(grp_cpy_xVectors_fu_46_in_Buffer_img_read),
    .xVector_dst_address0(grp_cpy_xVectors_fu_46_xVector_dst_address0),
    .xVector_dst_ce0(grp_cpy_xVectors_fu_46_xVector_dst_ce0),
    .xVector_dst_d0(grp_cpy_xVectors_fu_46_xVector_dst_d0),
    .xVector_dst_q0(32'd0),
    .xVector_dst_we0(grp_cpy_xVectors_fu_46_xVector_dst_we0),
    .xVector_dst_address1(grp_cpy_xVectors_fu_46_xVector_dst_address1),
    .xVector_dst_ce1(grp_cpy_xVectors_fu_46_xVector_dst_ce1),
    .xVector_dst_d1(grp_cpy_xVectors_fu_46_xVector_dst_d1),
    .xVector_dst_q1(32'd0),
    .xVector_dst_we1(grp_cpy_xVectors_fu_46_xVector_dst_we1),
    .out_Buffer_img_din(grp_cpy_xVectors_fu_46_out_Buffer_img_din),
    .out_Buffer_img_full_n(out_Buffer_img_full_n),
    .out_Buffer_img_write(grp_cpy_xVectors_fu_46_out_Buffer_img_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cpy_xVectors_fu_46_ap_start),
    .ap_done(grp_cpy_xVectors_fu_46_ap_done),
    .ap_ready(grp_cpy_xVectors_fu_46_ap_ready),
    .ap_idle(grp_cpy_xVectors_fu_46_ap_idle),
    .ap_continue(grp_cpy_xVectors_fu_46_ap_continue)
);

PROJECTION_projecting_Pipeline_proj_p_loop_proj_b_loop grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start),
    .ap_done(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done),
    .ap_idle(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_idle),
    .ap_ready(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_ready),
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_in_Buffer_img_read),
    .out_Buffer_img_din(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_din),
    .out_Buffer_img_full_n(out_Buffer_img_full_n),
    .out_Buffer_img_write(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_write),
    .Buffer_Proj_din(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_din),
    .Buffer_Proj_full_n(Buffer_Proj_full_n),
    .Buffer_Proj_write(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_write),
    .out_projection_din(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_din),
    .out_projection_full_n(out_projection_full_n),
    .out_projection_write(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_write),
    .p_uVector_address0(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_address0),
    .p_uVector_ce0(grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_ce0),
    .p_uVector_q0(p_uVector_q0),
    .zext_ln175(projectionScalingFactor_reg_99)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
            ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done <= 1'b0;
        end else if ((grp_cpy_xVectors_fu_46_ap_done == 1'b1)) begin
            ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
            ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready <= 1'b0;
        end else if ((grp_cpy_xVectors_fu_46_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cpy_xVectors_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state2) & (ap_sync_grp_cpy_xVectors_fu_46_ap_ready == 1'b0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
            grp_cpy_xVectors_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_cpy_xVectors_fu_46_ap_ready == 1'b1)) begin
            grp_cpy_xVectors_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_ready == 1'b1)) begin
            grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_reg_94 <= empty_fu_84_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        projectionScalingFactor_reg_99 <= projectionScalingFactor_fu_88_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Buffer_Proj_write = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_write;
    end else begin
        Buffer_Proj_write = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        grp_cpy_xVectors_fu_46_ap_continue = 1'b1;
    end else begin
        grp_cpy_xVectors_fu_46_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_Buffer_img_read = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_in_Buffer_img_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_Buffer_img_read = grp_cpy_xVectors_fu_46_in_Buffer_img_read;
    end else begin
        in_Buffer_img_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_Buffer_img_din = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_Buffer_img_din = grp_cpy_xVectors_fu_46_out_Buffer_img_din;
    end else begin
        out_Buffer_img_din = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_Buffer_img_write = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_Buffer_img_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_Buffer_img_write = grp_cpy_xVectors_fu_46_out_Buffer_img_write;
    end else begin
        out_Buffer_img_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_projection_write = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_write;
    end else begin
        out_projection_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_uVector_address0 = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_uVector_address0 = grp_cpy_xVectors_fu_46_xVector_dst_address0;
    end else begin
        p_uVector_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_uVector_ce0 = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_p_uVector_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_uVector_ce0 = grp_cpy_xVectors_fu_46_xVector_dst_ce0;
    end else begin
        p_uVector_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_uVector_we0 = grp_cpy_xVectors_fu_46_xVector_dst_we0;
    end else begin
        p_uVector_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Buffer_Proj_din = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_Buffer_Proj_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_grp_cpy_xVectors_fu_46_ap_ready & ap_sync_grp_cpy_xVectors_fu_46_ap_done) == 1'b0);
end

assign ap_sync_grp_cpy_xVectors_fu_46_ap_done = (grp_cpy_xVectors_fu_46_ap_done | ap_sync_reg_grp_cpy_xVectors_fu_46_ap_done);

assign ap_sync_grp_cpy_xVectors_fu_46_ap_ready = (grp_cpy_xVectors_fu_46_ap_ready | ap_sync_reg_grp_cpy_xVectors_fu_46_ap_ready);

assign empty_fu_84_p1 = shl_i_i_fu_78_p2[15:0];

assign grp_cpy_xVectors_fu_46_ap_start = grp_cpy_xVectors_fu_46_ap_start_reg;

assign grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_ap_start_reg;

assign out_projection_din = grp_projecting_Pipeline_proj_p_loop_proj_b_loop_fu_56_out_projection_din;

assign projectionScalingFactor_fu_88_p2 = ($signed(empty_reg_94) + $signed(16'd65535));

assign shl_i_i_fu_78_p2 = 32'd1 << sub_i_i_fu_72_p2;

assign sub_i_i_fu_72_p2 = ($signed(DRPROXECTIONS) + $signed(32'd4294967295));

endmodule //PROJECTION_projecting
