// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module Avg_dup_duplicateAndCentralizeImg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        imgBuff_out_din,
        imgBuff_out_full_n,
        imgBuff_out_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [15:0] imgBuff_out_din;
input   imgBuff_out_full_n;
output   imgBuff_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ImgBuff_in_read;
reg imgBuff_out_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] centroid_address0;
reg    centroid_ce0;
reg    centroid_we0;
wire   [15:0] centroid_q0;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_done;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_idle;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_ready;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ImgBuff_in_read;
wire   [3:0] grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_address0;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_ce0;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_we0;
wire   [15:0] grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_d0;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_idle;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_ready;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ImgBuff_in_read;
wire   [15:0] grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_din;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_write;
wire   [3:0] grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_address0;
wire    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_ce0;
reg    grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg = 1'b0;
#0 grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg = 1'b0;
end

Avg_dup_duplicateAndCentralizeImg_centroid_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
centroid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(centroid_address0),
    .ce0(centroid_ce0),
    .we0(centroid_we0),
    .d0(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_d0),
    .q0(centroid_q0)
);

Avg_dup_duplicateAndCentralizeImg_Pipeline_cent_storage grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start),
    .ap_done(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_done),
    .ap_idle(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_idle),
    .ap_ready(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_ready),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ImgBuff_in_read),
    .centroid_address0(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_address0),
    .centroid_ce0(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_ce0),
    .centroid_we0(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_we0),
    .centroid_d0(grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_d0)
);

Avg_dup_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start),
    .ap_done(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done),
    .ap_idle(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_idle),
    .ap_ready(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_ready),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ImgBuff_in_read),
    .imgBuff_out_din(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_din),
    .imgBuff_out_full_n(imgBuff_out_full_n),
    .imgBuff_out_write(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_write),
    .centroid_address0(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_address0),
    .centroid_ce0(grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_ce0),
    .centroid_q0(centroid_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_ready == 1'b1)) begin
            grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg <= 1'b1;
        end else if ((grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_ready == 1'b1)) begin
            grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ImgBuff_in_read = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ImgBuff_in_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ImgBuff_in_read = grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ImgBuff_in_read;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        centroid_address0 = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroid_address0 = grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_address0;
    end else begin
        centroid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        centroid_ce0 = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_centroid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroid_ce0 = grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_ce0;
    end else begin
        centroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        centroid_we0 = grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_centroid_we0;
    end else begin
        centroid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imgBuff_out_write = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_write;
    end else begin
        imgBuff_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_ap_start_reg;

assign grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start = grp_duplicateAndCentralizeImg_Pipeline_cent_storage_fu_26_ap_start_reg;

assign imgBuff_out_din = grp_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop_fu_34_imgBuff_out_din;

endmodule //Avg_dup_duplicateAndCentralizeImg
