// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Avg_dup_Avg_dup,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.160000,HLS_SYN_LAT=974,HLS_SYN_TPT=975,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=77,HLS_SYN_LUT=436,HLS_VERSION=2023_2}" *)

module Avg_dup (
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        imgBuff_out_din,
        imgBuff_out_full_n,
        imgBuff_out_write,
        stage3,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [15:0] imgBuff_out_din;
input   imgBuff_out_full_n;
output   imgBuff_out_write;
input  [0:0] stage3;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire    Block_entry1_proc_U0_ImgBuff_in_read;
wire   [15:0] Block_entry1_proc_U0_imgBuff_out_din;
wire    Block_entry1_proc_U0_imgBuff_out_write;

Avg_dup_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .stage3(stage3),
    .ImgBuff_in_dout(ImgBuff_in_dout),
    .ImgBuff_in_empty_n(ImgBuff_in_empty_n),
    .ImgBuff_in_read(Block_entry1_proc_U0_ImgBuff_in_read),
    .imgBuff_out_din(Block_entry1_proc_U0_imgBuff_out_din),
    .imgBuff_out_full_n(imgBuff_out_full_n),
    .imgBuff_out_write(Block_entry1_proc_U0_imgBuff_out_write)
);

assign Block_entry1_proc_U0_ap_continue = 1'b1;

assign Block_entry1_proc_U0_ap_start = ap_start;

assign ImgBuff_in_read = Block_entry1_proc_U0_ImgBuff_in_read;

assign ap_done = Block_entry1_proc_U0_ap_done;

assign ap_idle = Block_entry1_proc_U0_ap_idle;

assign ap_ready = Block_entry1_proc_U0_ap_ready;

assign imgBuff_out_din = Block_entry1_proc_U0_imgBuff_out_din;

assign imgBuff_out_write = Block_entry1_proc_U0_imgBuff_out_write;

endmodule //Avg_dup
