// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module Avg_dup_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgBuff_in_dout,
        ImgBuff_in_empty_n,
        ImgBuff_in_read,
        imgBuff_out_din,
        imgBuff_out_full_n,
        imgBuff_out_write,
        centroid_address0,
        centroid_ce0,
        centroid_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgBuff_in_dout;
input   ImgBuff_in_empty_n;
output   ImgBuff_in_read;
output  [15:0] imgBuff_out_din;
input   imgBuff_out_full_n;
output   imgBuff_out_write;
output  [3:0] centroid_address0;
output   centroid_ce0;
input  [15:0] centroid_q0;

reg ap_idle;
reg ImgBuff_in_read;
reg imgBuff_out_write;
reg centroid_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_93_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ImgBuff_in_blk_n;
wire    ap_block_pp0_stage0;
reg    imgBuff_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] select_ln79_fu_169_p3;
reg   [15:0] select_ln79_reg_200;
wire   [63:0] zext_ln79_fu_122_p1;
reg   [4:0] itBand_fu_46;
wire   [4:0] itBand_1_fu_127_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_itBand_load;
reg   [10:0] indvar_flatten_fu_50;
wire   [10:0] add_ln60_fu_99_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln62_fu_108_p2;
wire   [4:0] select_ln60_fu_114_p3;
wire  signed [15:0] sext_ln79_fu_143_p0;
wire   [16:0] centroid_load_cast_fu_147_p1;
wire  signed [16:0] sext_ln79_fu_143_p1;
wire  signed [15:0] sub_ln79_fu_157_p0;
wire  signed [15:0] sub_ln79_1_fu_163_p1;
wire   [0:0] icmp_ln79_fu_151_p2;
wire   [15:0] sub_ln79_fu_157_p2;
wire   [15:0] sub_ln79_1_fu_163_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 itBand_fu_46 = 5'd0;
#0 indvar_flatten_fu_50 = 11'd0;
#0 ap_done_reg = 1'b0;
end

Avg_dup_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_93_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_50 <= add_ln60_fu_99_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_50 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_93_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            itBand_fu_46 <= itBand_1_fu_127_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            itBand_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln79_reg_200 <= select_ln79_fu_169_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgBuff_in_blk_n = ImgBuff_in_empty_n;
    end else begin
        ImgBuff_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgBuff_in_read = 1'b1;
    end else begin
        ImgBuff_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_93_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_itBand_load = 5'd0;
    end else begin
        ap_sig_allocacmp_itBand_load = itBand_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        centroid_ce0 = 1'b1;
    end else begin
        centroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        imgBuff_out_blk_n = imgBuff_out_full_n;
    end else begin
        imgBuff_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        imgBuff_out_write = 1'b1;
    end else begin
        imgBuff_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_99_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == ImgBuff_in_empty_n);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (imgBuff_out_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign centroid_address0 = zext_ln79_fu_122_p1;

assign centroid_load_cast_fu_147_p1 = centroid_q0;

assign icmp_ln60_fu_93_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_108_p2 = ((ap_sig_allocacmp_itBand_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_151_p2 = (($signed(centroid_load_cast_fu_147_p1) < $signed(sext_ln79_fu_143_p1)) ? 1'b1 : 1'b0);

assign imgBuff_out_din = select_ln79_reg_200;

assign itBand_1_fu_127_p2 = (select_ln60_fu_114_p3 + 5'd1);

assign select_ln60_fu_114_p3 = ((icmp_ln62_fu_108_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_itBand_load);

assign select_ln79_fu_169_p3 = ((icmp_ln79_fu_151_p2[0:0] == 1'b1) ? sub_ln79_fu_157_p2 : sub_ln79_1_fu_163_p2);

assign sext_ln79_fu_143_p0 = ImgBuff_in_dout;

assign sext_ln79_fu_143_p1 = sext_ln79_fu_143_p0;

assign sub_ln79_1_fu_163_p1 = ImgBuff_in_dout;

assign sub_ln79_1_fu_163_p2 = ($signed(centroid_q0) - $signed(sub_ln79_1_fu_163_p1));

assign sub_ln79_fu_157_p0 = ImgBuff_in_dout;

assign sub_ln79_fu_157_p2 = ($signed(sub_ln79_fu_157_p0) - $signed(centroid_q0));

assign zext_ln79_fu_122_p1 = select_ln60_fu_114_p3;

endmodule //Avg_dup_duplicateAndCentralizeImg_Pipeline_cent_p_loop_cent_b_loop
