// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Avg_Cent_Avg_Cent,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.160000,HLS_SYN_LAT=975,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=580,HLS_SYN_LUT=628,HLS_VERSION=2023_2}" *)

module Avg_Cent (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgRef_dout,
        ImgRef_empty_n,
        ImgRef_read,
        out_centroid_din,
        out_centroid_full_n,
        out_centroid_write,
        stage3
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgRef_dout;
input   ImgRef_empty_n;
output   ImgRef_read;
output  [15:0] out_centroid_din;
input   out_centroid_full_n;
output   out_centroid_write;
input  [0:0] stage3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ImgRef_read;
reg out_centroid_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] stage3_read_read_fu_38_p2;
reg   [3:0] icentroid_address0;
reg    icentroid_ce0;
reg    icentroid_we0;
wire   [31:0] icentroid_q0;
reg    icentroid_ce1;
wire   [31:0] icentroid_q1;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_done;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_idle;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_ready;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ImgRef_read;
wire   [3:0] grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address0;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce0;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_we0;
wire   [31:0] grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_d0;
wire   [3:0] grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address1;
wire    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce1;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_done;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_idle;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_ready;
wire   [15:0] grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_din;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_write;
wire   [3:0] grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_address0;
wire    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_ce0;
reg    grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_block_state5_on_subcall_done;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg = 1'b0;
#0 grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg = 1'b0;
end

Avg_Cent_icentroid_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
icentroid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(icentroid_address0),
    .ce0(icentroid_ce0),
    .we0(icentroid_we0),
    .d0(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_d0),
    .q0(icentroid_q0),
    .address1(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address1),
    .ce1(icentroid_ce1),
    .q1(icentroid_q1)
);

Avg_Cent_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start),
    .ap_done(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_done),
    .ap_idle(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_idle),
    .ap_ready(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_ready),
    .ImgRef_dout(ImgRef_dout),
    .ImgRef_empty_n(ImgRef_empty_n),
    .ImgRef_read(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ImgRef_read),
    .icentroid_address0(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address0),
    .icentroid_ce0(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce0),
    .icentroid_we0(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_we0),
    .icentroid_d0(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_d0),
    .icentroid_address1(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address1),
    .icentroid_ce1(grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce1),
    .icentroid_q1(icentroid_q1)
);

Avg_Cent_Avg_Cent_Pipeline_cpy_cent grp_Avg_Cent_Pipeline_cpy_cent_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start),
    .ap_done(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_done),
    .ap_idle(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_idle),
    .ap_ready(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_ready),
    .out_centroid_din(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_din),
    .out_centroid_full_n(out_centroid_full_n),
    .out_centroid_write(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_write),
    .icentroid_address0(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_address0),
    .icentroid_ce0(grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_ce0),
    .icentroid_q0(icentroid_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_ready == 1'b1)) begin
            grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_ready == 1'b1)) begin
            grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ImgRef_read = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ImgRef_read;
    end else begin
        ImgRef_read = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        icentroid_address0 = grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        icentroid_address0 = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_address0;
    end else begin
        icentroid_address0 = 'bx;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        icentroid_ce0 = grp_Avg_Cent_Pipeline_cpy_cent_fu_52_icentroid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        icentroid_ce0 = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce0;
    end else begin
        icentroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icentroid_ce1 = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_ce1;
    end else begin
        icentroid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icentroid_we0 = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_icentroid_we0;
    end else begin
        icentroid_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        out_centroid_write = grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_write;
    end else begin
        out_centroid_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((stage3_read_read_fu_38_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((stage3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_done == 1'b0) & (stage3 == 1'd0));
end

assign grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start = grp_Avg_Cent_Pipeline_cpy_cent_fu_52_ap_start_reg;

assign grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start = grp_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop_fu_44_ap_start_reg;

assign out_centroid_din = grp_Avg_Cent_Pipeline_cpy_cent_fu_52_out_centroid_din;

assign stage3_read_read_fu_38_p2 = stage3;

endmodule //Avg_Cent
