// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module Avg_Cent_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgRef_dout,
        ImgRef_empty_n,
        ImgRef_read,
        icentroid_address0,
        icentroid_ce0,
        icentroid_we0,
        icentroid_d0,
        icentroid_address1,
        icentroid_ce1,
        icentroid_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgRef_dout;
input   ImgRef_empty_n;
output   ImgRef_read;
output  [3:0] icentroid_address0;
output   icentroid_ce0;
output   icentroid_we0;
output  [31:0] icentroid_d0;
output  [3:0] icentroid_address1;
output   icentroid_ce1;
input  [31:0] icentroid_q1;

reg ap_idle;
reg ImgRef_read;
reg icentroid_ce0;
reg icentroid_we0;
reg icentroid_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln18_fu_120_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ImgRef_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] select_ln18_1_fu_158_p3;
reg   [6:0] select_ln18_1_reg_283;
reg   [3:0] icentroid_addr_reg_289;
reg   [3:0] icentroid_addr_reg_289_pp0_iter1_reg;
reg   [3:0] icentroid_addr_reg_289_pp0_iter2_reg;
reg   [3:0] icentroid_addr_reg_289_pp0_iter3_reg;
reg   [3:0] icentroid_addr_reg_289_pp0_iter4_reg;
wire   [0:0] cmp10_i_fu_197_p2;
reg   [0:0] cmp10_i_reg_295;
reg   [0:0] cmp10_i_reg_295_pp0_iter2_reg;
reg   [0:0] cmp10_i_reg_295_pp0_iter3_reg;
wire   [31:0] add_ln33_fu_214_p2;
reg   [31:0] add_ln33_reg_300;
reg   [31:0] add_ln33_reg_300_pp0_iter2_reg;
reg   [31:0] add_ln33_reg_300_pp0_iter3_reg;
reg   [25:0] tmp_reg_311;
wire   [63:0] zext_ln20_fu_166_p1;
reg   [4:0] itBand_fu_58;
wire   [4:0] add_ln36_fu_171_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_itBand_load;
reg   [6:0] itPixel_fu_62;
reg   [6:0] ap_sig_allocacmp_itPixel_load;
reg   [10:0] indvar_flatten_fu_66;
wire   [10:0] add_ln18_fu_126_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] newPixel0_1_fu_70;
wire   [31:0] newPixel0_fu_237_p3;
wire   [31:0] grp_fu_97_p0;
wire   [33:0] grp_fu_97_p1;
wire   [0:0] icmp_ln20_fu_138_p2;
wire   [6:0] add_ln18_1_fu_152_p2;
wire   [4:0] select_ln18_fu_144_p3;
wire   [0:0] cmp7_i_fu_192_p2;
wire   [31:0] prev0_fu_202_p3;
wire   [31:0] zext_ln33_fu_210_p1;
wire   [64:0] grp_fu_97_p2;
wire   [31:0] zext_ln33_2_fu_234_p1;
reg    grp_fu_97_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [64:0] grp_fu_97_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 itBand_fu_58 = 5'd0;
#0 itPixel_fu_62 = 7'd0;
#0 indvar_flatten_fu_66 = 11'd0;
#0 newPixel0_1_fu_70 = 32'd0;
#0 ap_done_reg = 1'b0;
end

Avg_Cent_mul_32ns_34ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_97_p0),
    .din1(grp_fu_97_p1),
    .ce(grp_fu_97_ce),
    .dout(grp_fu_97_p2)
);

Avg_Cent_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln18_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_66 <= add_ln18_fu_126_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_66 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln18_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            itBand_fu_58 <= add_ln36_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            itBand_fu_58 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln18_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            itPixel_fu_62 <= select_ln18_1_fu_158_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            itPixel_fu_62 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln33_reg_300 <= add_ln33_fu_214_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp10_i_reg_295 <= cmp10_i_fu_197_p2;
        icentroid_addr_reg_289 <= zext_ln20_fu_166_p1;
        icentroid_addr_reg_289_pp0_iter1_reg <= icentroid_addr_reg_289;
        select_ln18_1_reg_283 <= select_ln18_1_fu_158_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln33_reg_300_pp0_iter2_reg <= add_ln33_reg_300;
        add_ln33_reg_300_pp0_iter3_reg <= add_ln33_reg_300_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        cmp10_i_reg_295_pp0_iter2_reg <= cmp10_i_reg_295;
        cmp10_i_reg_295_pp0_iter3_reg <= cmp10_i_reg_295_pp0_iter2_reg;
        icentroid_addr_reg_289_pp0_iter2_reg <= icentroid_addr_reg_289_pp0_iter1_reg;
        icentroid_addr_reg_289_pp0_iter3_reg <= icentroid_addr_reg_289_pp0_iter2_reg;
        icentroid_addr_reg_289_pp0_iter4_reg <= icentroid_addr_reg_289_pp0_iter3_reg;
        tmp_reg_311 <= {{grp_fu_97_p2[64:39]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        newPixel0_1_fu_70 <= newPixel0_fu_237_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgRef_blk_n = ImgRef_empty_n;
    end else begin
        ImgRef_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ImgRef_read = 1'b1;
    end else begin
        ImgRef_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln18_fu_120_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_itBand_load = 5'd0;
    end else begin
        ap_sig_allocacmp_itBand_load = itBand_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_itPixel_load = 7'd0;
    end else begin
        ap_sig_allocacmp_itPixel_load = itPixel_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_97_ce = 1'b1;
    end else begin
        grp_fu_97_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        icentroid_ce0 = 1'b1;
    end else begin
        icentroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icentroid_ce1 = 1'b1;
    end else begin
        icentroid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        icentroid_we0 = 1'b1;
    end else begin
        icentroid_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_1_fu_152_p2 = (ap_sig_allocacmp_itPixel_load + 7'd1);

assign add_ln18_fu_126_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln33_fu_214_p2 = (prev0_fu_202_p3 + zext_ln33_fu_210_p1);

assign add_ln36_fu_171_p2 = (select_ln18_fu_144_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == ImgRef_empty_n);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp10_i_fu_197_p2 = ((select_ln18_1_reg_283 == 7'd119) ? 1'b1 : 1'b0);

assign cmp7_i_fu_192_p2 = ((select_ln18_1_reg_283 == 7'd0) ? 1'b1 : 1'b0);

assign grp_fu_97_p0 = grp_fu_97_p00;

assign grp_fu_97_p00 = add_ln33_reg_300;

assign grp_fu_97_p1 = 65'd4581298450;

assign icentroid_address0 = icentroid_addr_reg_289_pp0_iter4_reg;

assign icentroid_address1 = zext_ln20_fu_166_p1;

assign icentroid_d0 = newPixel0_1_fu_70;

assign icmp_ln18_fu_120_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_138_p2 = ((ap_sig_allocacmp_itBand_load == 5'd16) ? 1'b1 : 1'b0);

assign newPixel0_fu_237_p3 = ((cmp10_i_reg_295_pp0_iter3_reg[0:0] == 1'b1) ? zext_ln33_2_fu_234_p1 : add_ln33_reg_300_pp0_iter3_reg);

assign prev0_fu_202_p3 = ((cmp7_i_fu_192_p2[0:0] == 1'b1) ? 32'd0 : icentroid_q1);

assign select_ln18_1_fu_158_p3 = ((icmp_ln20_fu_138_p2[0:0] == 1'b1) ? add_ln18_1_fu_152_p2 : ap_sig_allocacmp_itPixel_load);

assign select_ln18_fu_144_p3 = ((icmp_ln20_fu_138_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_itBand_load);

assign zext_ln20_fu_166_p1 = select_ln18_fu_144_p3;

assign zext_ln33_2_fu_234_p1 = tmp_reg_311;

assign zext_ln33_fu_210_p1 = ImgRef_dout;

endmodule //Avg_Cent_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop
