// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module SUBTRACTION_cpy_xVectors_Loop_VITIS_LOOP_120_1_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        xVector_dst_address0,
        xVector_dst_ce0,
        xVector_dst_we0,
        xVector_dst_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [3:0] xVector_dst_address0;
output   xVector_dst_ce0;
output   xVector_dst_we0;
output  [31:0] xVector_dst_d0;

reg ap_idle;
reg in_Buffer_img_read;
reg xVector_dst_ce0;
reg xVector_dst_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln120_fu_76_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_Buffer_img_blk_n;
wire   [63:0] zext_ln120_fu_88_p1;
reg   [5:0] itBands_fu_44;
wire   [5:0] add_ln120_fu_82_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_itBands_1;
wire   [0:0] icmp_fu_103_p2;
wire   [1:0] tmp_fu_93_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 itBands_fu_44 = 6'd0;
end

SUBTRACTION_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln120_fu_76_p2 == 1'd0)) begin
            itBands_fu_44 <= add_ln120_fu_82_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            itBands_fu_44 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln120_fu_76_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_itBands_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_itBands_1 = itBands_fu_44;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (icmp_ln120_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_Buffer_img_blk_n = in_Buffer_img_empty_n;
    end else begin
        in_Buffer_img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln120_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_Buffer_img_read = 1'b1;
    end else begin
        in_Buffer_img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        xVector_dst_ce0 = 1'b1;
    end else begin
        xVector_dst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_fu_103_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln120_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        xVector_dst_we0 = 1'b1;
    end else begin
        xVector_dst_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln120_fu_82_p2 = (ap_sig_allocacmp_itBands_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((icmp_ln120_fu_76_p2 == 1'd0) & (in_Buffer_img_empty_n == 1'b0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_fu_103_p2 = ((tmp_fu_93_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_76_p2 = ((ap_sig_allocacmp_itBands_1 == 6'd32) ? 1'b1 : 1'b0);

assign tmp_fu_93_p4 = {{ap_sig_allocacmp_itBands_1[5:4]}};

assign xVector_dst_address0 = zext_ln120_fu_88_p1;

assign xVector_dst_d0 = in_Buffer_img_dout;

assign zext_ln120_fu_88_p1 = ap_sig_allocacmp_itBands_1;

endmodule //SUBTRACTION_cpy_xVectors_Loop_VITIS_LOOP_120_1_proc1
