// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module SUBTRACTION_subtracting (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_Buffer_img_dout,
        in_Buffer_img_empty_n,
        in_Buffer_img_read,
        out_Buffer_img_din,
        out_Buffer_img_full_n,
        out_Buffer_img_write,
        projection_dout,
        projection_empty_n,
        projection_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_Buffer_img_dout;
input   in_Buffer_img_empty_n;
output   in_Buffer_img_read;
output  [15:0] out_Buffer_img_din;
input   out_Buffer_img_full_n;
output   out_Buffer_img_write;
input  [31:0] projection_dout;
input   projection_empty_n;
output   projection_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_Buffer_img_read;
reg out_Buffer_img_write;
reg projection_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] projectionValueLong;
reg    in_Buffer_img_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg    out_Buffer_img_blk_n;
reg    projection_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln288_reg_239;
wire   [0:0] icmp_ln288_fu_160_p2;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] p_qVector_q0;
reg  signed [31:0] qValueLong_reg_248;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state2;
wire    grp_cpy_xVectors_fu_101_ap_done;
wire    grp_cpy_xVectors_fu_101_ap_ready;
wire    ap_sync_grp_cpy_xVectors_fu_101_ap_ready;
wire    ap_sync_grp_cpy_xVectors_fu_101_ap_done;
reg    ap_block_state2_on_subcall_done;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln282_fu_126_p2;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [3:0] p_qVector_address0;
reg    p_qVector_ce0;
reg    p_qVector_we0;
wire    grp_cpy_xVectors_fu_101_in_Buffer_img_read;
wire   [3:0] grp_cpy_xVectors_fu_101_xVector_dst_address0;
wire    grp_cpy_xVectors_fu_101_xVector_dst_ce0;
wire   [31:0] grp_cpy_xVectors_fu_101_xVector_dst_d0;
wire    grp_cpy_xVectors_fu_101_xVector_dst_we0;
wire   [3:0] grp_cpy_xVectors_fu_101_xVector_dst_address1;
wire    grp_cpy_xVectors_fu_101_xVector_dst_ce1;
wire   [31:0] grp_cpy_xVectors_fu_101_xVector_dst_d1;
wire    grp_cpy_xVectors_fu_101_xVector_dst_we1;
wire    grp_cpy_xVectors_fu_101_ap_start;
wire    grp_cpy_xVectors_fu_101_ap_idle;
reg    grp_cpy_xVectors_fu_101_ap_continue;
reg    grp_cpy_xVectors_fu_101_ap_start_reg;
reg    ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready;
reg    ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done;
wire   [63:0] zext_ln284_fu_155_p1;
reg   [4:0] itBand_fu_58;
wire   [4:0] add_ln284_fu_166_p2;
reg   [10:0] indvar_flatten_fu_62;
wire   [10:0] add_ln282_fu_132_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln284_fu_141_p2;
wire   [4:0] select_ln282_fu_147_p3;
wire   [43:0] mul_ln304_fu_109_p2;
wire   [15:0] pixb_fu_188_p1;
wire   [15:0] trunc_ln_fu_205_p4;
wire    ap_CS_fsm_state6;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 projectionValueLong = 32'd0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_cpy_xVectors_fu_101_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready = 1'b0;
#0 ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done = 1'b0;
#0 itBand_fu_58 = 5'd0;
#0 indvar_flatten_fu_62 = 11'd0;
end

SUBTRACTION_subtracting_p_qVector_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_qVector_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_qVector_address0),
    .ce0(p_qVector_ce0),
    .we0(p_qVector_we0),
    .d0(grp_cpy_xVectors_fu_101_xVector_dst_d0),
    .q0(p_qVector_q0)
);

SUBTRACTION_cpy_xVectors grp_cpy_xVectors_fu_101(
    .in_Buffer_img_dout(in_Buffer_img_dout),
    .in_Buffer_img_empty_n(in_Buffer_img_empty_n),
    .in_Buffer_img_read(grp_cpy_xVectors_fu_101_in_Buffer_img_read),
    .xVector_dst_address0(grp_cpy_xVectors_fu_101_xVector_dst_address0),
    .xVector_dst_ce0(grp_cpy_xVectors_fu_101_xVector_dst_ce0),
    .xVector_dst_d0(grp_cpy_xVectors_fu_101_xVector_dst_d0),
    .xVector_dst_q0(32'd0),
    .xVector_dst_we0(grp_cpy_xVectors_fu_101_xVector_dst_we0),
    .xVector_dst_address1(grp_cpy_xVectors_fu_101_xVector_dst_address1),
    .xVector_dst_ce1(grp_cpy_xVectors_fu_101_xVector_dst_ce1),
    .xVector_dst_d1(grp_cpy_xVectors_fu_101_xVector_dst_d1),
    .xVector_dst_q1(32'd0),
    .xVector_dst_we1(grp_cpy_xVectors_fu_101_xVector_dst_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cpy_xVectors_fu_101_ap_start),
    .ap_done(grp_cpy_xVectors_fu_101_ap_done),
    .ap_ready(grp_cpy_xVectors_fu_101_ap_ready),
    .ap_idle(grp_cpy_xVectors_fu_101_ap_idle),
    .ap_continue(grp_cpy_xVectors_fu_101_ap_continue)
);

SUBTRACTION_mul_32s_32s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 44 ))
mul_32s_32s_44_1_1_U5(
    .din0(qValueLong_reg_248),
    .din1(projectionValueLong),
    .dout(mul_ln304_fu_109_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done <= 1'b0;
        end else if ((grp_cpy_xVectors_fu_101_ap_done == 1'b1)) begin
            ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready <= 1'b0;
        end else if ((grp_cpy_xVectors_fu_101_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cpy_xVectors_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_sync_grp_cpy_xVectors_fu_101_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
            grp_cpy_xVectors_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_cpy_xVectors_fu_101_ap_ready == 1'b1)) begin
            grp_cpy_xVectors_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_62 <= 11'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln282_fu_126_p2 == 1'd0))) begin
        indvar_flatten_fu_62 <= add_ln282_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        itBand_fu_58 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln282_fu_126_p2 == 1'd0))) begin
        itBand_fu_58 <= add_ln284_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln288_reg_239 <= icmp_ln288_fu_160_p2;
        qValueLong_reg_248 <= p_qVector_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln288_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projectionValueLong <= projection_dout;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln282_fu_126_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_cpy_xVectors_fu_101_ap_continue = 1'b1;
    end else begin
        grp_cpy_xVectors_fu_101_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_Buffer_img_blk_n = in_Buffer_img_empty_n;
    end else begin
        in_Buffer_img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_Buffer_img_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_Buffer_img_read = grp_cpy_xVectors_fu_101_in_Buffer_img_read;
    end else begin
        in_Buffer_img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_Buffer_img_blk_n = out_Buffer_img_full_n;
    end else begin
        out_Buffer_img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_Buffer_img_write = 1'b1;
    end else begin
        out_Buffer_img_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_qVector_address0 = zext_ln284_fu_155_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_qVector_address0 = grp_cpy_xVectors_fu_101_xVector_dst_address0;
    end else begin
        p_qVector_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_qVector_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_qVector_ce0 = grp_cpy_xVectors_fu_101_xVector_dst_ce0;
    end else begin
        p_qVector_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_qVector_we0 = grp_cpy_xVectors_fu_101_xVector_dst_we0;
    end else begin
        p_qVector_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln288_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_blk_n = projection_empty_n;
    end else begin
        projection_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln288_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_read = 1'b1;
    end else begin
        projection_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln282_fu_126_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln282_fu_126_p2 == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln282_fu_132_p2 = (indvar_flatten_fu_62 + 11'd1);

assign add_ln284_fu_166_p2 = (select_ln282_fu_147_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_grp_cpy_xVectors_fu_101_ap_ready & ap_sync_grp_cpy_xVectors_fu_101_ap_done) == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((icmp_ln288_reg_239 == 1'd1) & (projection_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = ((out_Buffer_img_full_n == 1'b0) | (in_Buffer_img_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_sync_grp_cpy_xVectors_fu_101_ap_done = (grp_cpy_xVectors_fu_101_ap_done | ap_sync_reg_grp_cpy_xVectors_fu_101_ap_done);

assign ap_sync_grp_cpy_xVectors_fu_101_ap_ready = (grp_cpy_xVectors_fu_101_ap_ready | ap_sync_reg_grp_cpy_xVectors_fu_101_ap_ready);

assign grp_cpy_xVectors_fu_101_ap_start = grp_cpy_xVectors_fu_101_ap_start_reg;

assign icmp_ln282_fu_126_p2 = ((indvar_flatten_fu_62 == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_141_p2 = ((itBand_fu_58 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln288_fu_160_p2 = ((select_ln282_fu_147_p3 == 5'd0) ? 1'b1 : 1'b0);

assign out_Buffer_img_din = (pixb_fu_188_p1 - trunc_ln_fu_205_p4);

assign pixb_fu_188_p1 = in_Buffer_img_dout[15:0];

assign select_ln282_fu_147_p3 = ((icmp_ln284_fu_141_p2[0:0] == 1'b1) ? 5'd0 : itBand_fu_58);

assign trunc_ln_fu_205_p4 = {{mul_ln304_fu_109_p2[43:28]}};

assign zext_ln284_fu_155_p1 = select_ln282_fu_147_p3;

endmodule //SUBTRACTION_subtracting
