// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package power_manager_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 8;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic q;} power_manager_reg2hw_wakeup_state_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_restore_address_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_global_pointer_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_en_wait_for_intr_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_intr_state_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_core_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_core_ack_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_reset_assert_counter_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_reset_deassert_counter_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_switch_off_counter_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_switch_on_counter_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_cpu_wait_ack_switch_on_counter_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_iso_off_counter_reg_t;

  typedef struct packed {logic [31:0] q;} power_manager_reg2hw_cpu_iso_on_counter_reg_t;

  typedef struct packed {
    struct packed {logic q;} cpu_reset_assert_stop_bit_counter;
    struct packed {logic q;} cpu_reset_deassert_stop_bit_counter;
    struct packed {logic q;} cpu_switch_off_stop_bit_counter;
    struct packed {logic q;} cpu_switch_on_stop_bit_counter;
    struct packed {logic q;} cpu_iso_off_stop_bit_counter;
    struct packed {logic q;} cpu_iso_on_stop_bit_counter;
  } power_manager_reg2hw_cpu_counters_stop_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_periph_ack_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_periph_reset_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_periph_switch_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_periph_wait_ack_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_periph_iso_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_periph_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_dma_ch0_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_dma_ch1_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_dma_ch2_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_dma_ch3_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_0_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_ram_block_0_ack_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_0_switch_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_0_wait_ack_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_0_iso_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_0_retentive_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_1_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_ram_block_1_ack_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_1_switch_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_1_wait_ack_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_1_iso_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_1_retentive_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_2_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_ram_block_2_ack_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_2_switch_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_2_wait_ack_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_2_iso_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_2_retentive_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_3_clk_gate_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_power_gate_ram_block_3_ack_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_3_switch_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_3_wait_ack_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_3_iso_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_ram_3_retentive_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_switch_off_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_switch_on_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_reset_assert_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_reset_deassert_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_iso_off_reg_t;

  typedef struct packed {logic q;} power_manager_reg2hw_master_cpu_force_iso_on_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_intr_state_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_core_ack_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_reset_assert_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_reset_deassert_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_switch_off_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_switch_on_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_iso_off_counter_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } power_manager_hw2reg_cpu_iso_on_counter_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_periph_ack_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_ram_block_0_ack_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_ram_block_1_ack_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_ram_block_2_ack_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } power_manager_hw2reg_power_gate_ram_block_3_ack_reg_t;

  typedef struct packed {
    logic [2:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_core_reg_t;

  typedef struct packed {
    logic [2:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_periph_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_ram_block_0_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_ram_block_1_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_ram_block_2_reg_t;

  typedef struct packed {
    logic [1:0] d;
    logic       de;
  } power_manager_hw2reg_monitor_power_gate_ram_block_3_reg_t;

  // Register -> HW type
  typedef struct packed {
    power_manager_reg2hw_wakeup_state_reg_t wakeup_state;  // [369:369]
    power_manager_reg2hw_restore_address_reg_t restore_address;  // [368:337]
    power_manager_reg2hw_global_pointer_reg_t global_pointer;  // [336:305]
    power_manager_reg2hw_en_wait_for_intr_reg_t en_wait_for_intr;  // [304:273]
    power_manager_reg2hw_intr_state_reg_t intr_state;  // [272:241]
    power_manager_reg2hw_power_gate_core_reg_t power_gate_core;  // [240:240]
    power_manager_reg2hw_power_gate_core_ack_reg_t power_gate_core_ack;  // [239:239]
    power_manager_reg2hw_cpu_reset_assert_counter_reg_t cpu_reset_assert_counter;  // [238:207]
    power_manager_reg2hw_cpu_reset_deassert_counter_reg_t cpu_reset_deassert_counter;  // [206:175]
    power_manager_reg2hw_cpu_switch_off_counter_reg_t cpu_switch_off_counter;  // [174:143]
    power_manager_reg2hw_cpu_switch_on_counter_reg_t cpu_switch_on_counter;  // [142:111]
    power_manager_reg2hw_cpu_wait_ack_switch_on_counter_reg_t cpu_wait_ack_switch_on_counter; // [110:110]
    power_manager_reg2hw_cpu_iso_off_counter_reg_t cpu_iso_off_counter;  // [109:78]
    power_manager_reg2hw_cpu_iso_on_counter_reg_t cpu_iso_on_counter;  // [77:46]
    power_manager_reg2hw_cpu_counters_stop_reg_t cpu_counters_stop;  // [45:40]
    power_manager_reg2hw_power_gate_periph_ack_reg_t power_gate_periph_ack;  // [39:39]
    power_manager_reg2hw_periph_reset_reg_t periph_reset;  // [38:38]
    power_manager_reg2hw_periph_switch_reg_t periph_switch;  // [37:37]
    power_manager_reg2hw_periph_wait_ack_switch_on_reg_t periph_wait_ack_switch_on;  // [36:36]
    power_manager_reg2hw_periph_iso_reg_t periph_iso;  // [35:35]
    power_manager_reg2hw_periph_clk_gate_reg_t periph_clk_gate;  // [34:34]
    power_manager_reg2hw_dma_ch0_clk_gate_reg_t dma_ch0_clk_gate;  // [33:33]
    power_manager_reg2hw_dma_ch1_clk_gate_reg_t dma_ch1_clk_gate;  // [32:32]
    power_manager_reg2hw_dma_ch2_clk_gate_reg_t dma_ch2_clk_gate;  // [31:31]
    power_manager_reg2hw_dma_ch3_clk_gate_reg_t dma_ch3_clk_gate;  // [30:30]
    power_manager_reg2hw_ram_0_clk_gate_reg_t ram_0_clk_gate;  // [29:29]
    power_manager_reg2hw_power_gate_ram_block_0_ack_reg_t power_gate_ram_block_0_ack;  // [28:28]
    power_manager_reg2hw_ram_0_switch_reg_t ram_0_switch;  // [27:27]
    power_manager_reg2hw_ram_0_wait_ack_switch_on_reg_t ram_0_wait_ack_switch_on;  // [26:26]
    power_manager_reg2hw_ram_0_iso_reg_t ram_0_iso;  // [25:25]
    power_manager_reg2hw_ram_0_retentive_reg_t ram_0_retentive;  // [24:24]
    power_manager_reg2hw_ram_1_clk_gate_reg_t ram_1_clk_gate;  // [23:23]
    power_manager_reg2hw_power_gate_ram_block_1_ack_reg_t power_gate_ram_block_1_ack;  // [22:22]
    power_manager_reg2hw_ram_1_switch_reg_t ram_1_switch;  // [21:21]
    power_manager_reg2hw_ram_1_wait_ack_switch_on_reg_t ram_1_wait_ack_switch_on;  // [20:20]
    power_manager_reg2hw_ram_1_iso_reg_t ram_1_iso;  // [19:19]
    power_manager_reg2hw_ram_1_retentive_reg_t ram_1_retentive;  // [18:18]
    power_manager_reg2hw_ram_2_clk_gate_reg_t ram_2_clk_gate;  // [17:17]
    power_manager_reg2hw_power_gate_ram_block_2_ack_reg_t power_gate_ram_block_2_ack;  // [16:16]
    power_manager_reg2hw_ram_2_switch_reg_t ram_2_switch;  // [15:15]
    power_manager_reg2hw_ram_2_wait_ack_switch_on_reg_t ram_2_wait_ack_switch_on;  // [14:14]
    power_manager_reg2hw_ram_2_iso_reg_t ram_2_iso;  // [13:13]
    power_manager_reg2hw_ram_2_retentive_reg_t ram_2_retentive;  // [12:12]
    power_manager_reg2hw_ram_3_clk_gate_reg_t ram_3_clk_gate;  // [11:11]
    power_manager_reg2hw_power_gate_ram_block_3_ack_reg_t power_gate_ram_block_3_ack;  // [10:10]
    power_manager_reg2hw_ram_3_switch_reg_t ram_3_switch;  // [9:9]
    power_manager_reg2hw_ram_3_wait_ack_switch_on_reg_t ram_3_wait_ack_switch_on;  // [8:8]
    power_manager_reg2hw_ram_3_iso_reg_t ram_3_iso;  // [7:7]
    power_manager_reg2hw_ram_3_retentive_reg_t ram_3_retentive;  // [6:6]
    power_manager_reg2hw_master_cpu_force_switch_off_reg_t master_cpu_force_switch_off;  // [5:5]
    power_manager_reg2hw_master_cpu_force_switch_on_reg_t master_cpu_force_switch_on;  // [4:4]
    power_manager_reg2hw_master_cpu_force_reset_assert_reg_t master_cpu_force_reset_assert; // [3:3]
    power_manager_reg2hw_master_cpu_force_reset_deassert_reg_t master_cpu_force_reset_deassert; // [2:2]
    power_manager_reg2hw_master_cpu_force_iso_off_reg_t master_cpu_force_iso_off;  // [1:1]
    power_manager_reg2hw_master_cpu_force_iso_on_reg_t master_cpu_force_iso_on;  // [0:0]
  } power_manager_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    power_manager_hw2reg_intr_state_reg_t intr_state;  // [262:230]
    power_manager_hw2reg_power_gate_core_ack_reg_t power_gate_core_ack;  // [229:228]
    power_manager_hw2reg_cpu_reset_assert_counter_reg_t cpu_reset_assert_counter;  // [227:195]
    power_manager_hw2reg_cpu_reset_deassert_counter_reg_t cpu_reset_deassert_counter;  // [194:162]
    power_manager_hw2reg_cpu_switch_off_counter_reg_t cpu_switch_off_counter;  // [161:129]
    power_manager_hw2reg_cpu_switch_on_counter_reg_t cpu_switch_on_counter;  // [128:96]
    power_manager_hw2reg_cpu_iso_off_counter_reg_t cpu_iso_off_counter;  // [95:63]
    power_manager_hw2reg_cpu_iso_on_counter_reg_t cpu_iso_on_counter;  // [62:30]
    power_manager_hw2reg_power_gate_periph_ack_reg_t power_gate_periph_ack;  // [29:28]
    power_manager_hw2reg_power_gate_ram_block_0_ack_reg_t power_gate_ram_block_0_ack;  // [27:26]
    power_manager_hw2reg_power_gate_ram_block_1_ack_reg_t power_gate_ram_block_1_ack;  // [25:24]
    power_manager_hw2reg_power_gate_ram_block_2_ack_reg_t power_gate_ram_block_2_ack;  // [23:22]
    power_manager_hw2reg_power_gate_ram_block_3_ack_reg_t power_gate_ram_block_3_ack;  // [21:20]
    power_manager_hw2reg_monitor_power_gate_core_reg_t monitor_power_gate_core;  // [19:16]
    power_manager_hw2reg_monitor_power_gate_periph_reg_t monitor_power_gate_periph;  // [15:12]
    power_manager_hw2reg_monitor_power_gate_ram_block_0_reg_t monitor_power_gate_ram_block_0; // [11:9]
    power_manager_hw2reg_monitor_power_gate_ram_block_1_reg_t monitor_power_gate_ram_block_1; // [8:6]
    power_manager_hw2reg_monitor_power_gate_ram_block_2_reg_t monitor_power_gate_ram_block_2; // [5:3]
    power_manager_hw2reg_monitor_power_gate_ram_block_3_reg_t monitor_power_gate_ram_block_3; // [2:0]
  } power_manager_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] POWER_MANAGER_WAKEUP_STATE_OFFSET = 8'h0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RESTORE_ADDRESS_OFFSET = 8'h4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_GLOBAL_POINTER_OFFSET = 8'h8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_EN_WAIT_FOR_INTR_OFFSET = 8'hc;
  parameter logic [BlockAw-1:0] POWER_MANAGER_INTR_STATE_OFFSET = 8'h10;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_CORE_OFFSET = 8'h14;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_CORE_ACK_OFFSET = 8'h18;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_RESET_ASSERT_COUNTER_OFFSET = 8'h1c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_RESET_DEASSERT_COUNTER_OFFSET = 8'h20;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_SWITCH_OFF_COUNTER_OFFSET = 8'h24;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_SWITCH_ON_COUNTER_OFFSET = 8'h28;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_WAIT_ACK_SWITCH_ON_COUNTER_OFFSET = 8'h2c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_ISO_OFF_COUNTER_OFFSET = 8'h30;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_ISO_ON_COUNTER_OFFSET = 8'h34;
  parameter logic [BlockAw-1:0] POWER_MANAGER_CPU_COUNTERS_STOP_OFFSET = 8'h38;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_PERIPH_ACK_OFFSET = 8'h3c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_PERIPH_RESET_OFFSET = 8'h40;
  parameter logic [BlockAw-1:0] POWER_MANAGER_PERIPH_SWITCH_OFFSET = 8'h44;
  parameter logic [BlockAw-1:0] POWER_MANAGER_PERIPH_WAIT_ACK_SWITCH_ON_OFFSET = 8'h48;
  parameter logic [BlockAw-1:0] POWER_MANAGER_PERIPH_ISO_OFFSET = 8'h4c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_PERIPH_CLK_GATE_OFFSET = 8'h50;
  parameter logic [BlockAw-1:0] POWER_MANAGER_DMA_CH0_CLK_GATE_OFFSET = 8'h54;
  parameter logic [BlockAw-1:0] POWER_MANAGER_DMA_CH1_CLK_GATE_OFFSET = 8'h58;
  parameter logic [BlockAw-1:0] POWER_MANAGER_DMA_CH2_CLK_GATE_OFFSET = 8'h5c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_DMA_CH3_CLK_GATE_OFFSET = 8'h60;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_0_CLK_GATE_OFFSET = 8'h64;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_RAM_BLOCK_0_ACK_OFFSET = 8'h68;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_0_SWITCH_OFFSET = 8'h6c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_0_WAIT_ACK_SWITCH_ON_OFFSET = 8'h70;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_0_ISO_OFFSET = 8'h74;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_0_RETENTIVE_OFFSET = 8'h78;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_1_CLK_GATE_OFFSET = 8'h7c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_RAM_BLOCK_1_ACK_OFFSET = 8'h80;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_1_SWITCH_OFFSET = 8'h84;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_1_WAIT_ACK_SWITCH_ON_OFFSET = 8'h88;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_1_ISO_OFFSET = 8'h8c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_1_RETENTIVE_OFFSET = 8'h90;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_2_CLK_GATE_OFFSET = 8'h94;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_RAM_BLOCK_2_ACK_OFFSET = 8'h98;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_2_SWITCH_OFFSET = 8'h9c;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_2_WAIT_ACK_SWITCH_ON_OFFSET = 8'ha0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_2_ISO_OFFSET = 8'ha4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_2_RETENTIVE_OFFSET = 8'ha8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_3_CLK_GATE_OFFSET = 8'hac;
  parameter logic [BlockAw-1:0] POWER_MANAGER_POWER_GATE_RAM_BLOCK_3_ACK_OFFSET = 8'hb0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_3_SWITCH_OFFSET = 8'hb4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_3_WAIT_ACK_SWITCH_ON_OFFSET = 8'hb8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_3_ISO_OFFSET = 8'hbc;
  parameter logic [BlockAw-1:0] POWER_MANAGER_RAM_3_RETENTIVE_OFFSET = 8'hc0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_CORE_OFFSET = 8'hc4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_PERIPH_OFFSET = 8'hc8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_0_OFFSET = 8'hcc;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_1_OFFSET = 8'hd0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_2_OFFSET = 8'hd4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_3_OFFSET = 8'hd8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_OFF_OFFSET = 8'hdc;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_ON_OFFSET = 8'he0;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_RESET_ASSERT_OFFSET = 8'he4;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_RESET_DEASSERT_OFFSET = 8'he8;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_ISO_OFF_OFFSET = 8'hec;
  parameter logic [BlockAw-1:0] POWER_MANAGER_MASTER_CPU_FORCE_ISO_ON_OFFSET = 8'hf0;

  // Register index
  typedef enum int {
    POWER_MANAGER_WAKEUP_STATE,
    POWER_MANAGER_RESTORE_ADDRESS,
    POWER_MANAGER_GLOBAL_POINTER,
    POWER_MANAGER_EN_WAIT_FOR_INTR,
    POWER_MANAGER_INTR_STATE,
    POWER_MANAGER_POWER_GATE_CORE,
    POWER_MANAGER_POWER_GATE_CORE_ACK,
    POWER_MANAGER_CPU_RESET_ASSERT_COUNTER,
    POWER_MANAGER_CPU_RESET_DEASSERT_COUNTER,
    POWER_MANAGER_CPU_SWITCH_OFF_COUNTER,
    POWER_MANAGER_CPU_SWITCH_ON_COUNTER,
    POWER_MANAGER_CPU_WAIT_ACK_SWITCH_ON_COUNTER,
    POWER_MANAGER_CPU_ISO_OFF_COUNTER,
    POWER_MANAGER_CPU_ISO_ON_COUNTER,
    POWER_MANAGER_CPU_COUNTERS_STOP,
    POWER_MANAGER_POWER_GATE_PERIPH_ACK,
    POWER_MANAGER_PERIPH_RESET,
    POWER_MANAGER_PERIPH_SWITCH,
    POWER_MANAGER_PERIPH_WAIT_ACK_SWITCH_ON,
    POWER_MANAGER_PERIPH_ISO,
    POWER_MANAGER_PERIPH_CLK_GATE,
    POWER_MANAGER_DMA_CH0_CLK_GATE,
    POWER_MANAGER_DMA_CH1_CLK_GATE,
    POWER_MANAGER_DMA_CH2_CLK_GATE,
    POWER_MANAGER_DMA_CH3_CLK_GATE,
    POWER_MANAGER_RAM_0_CLK_GATE,
    POWER_MANAGER_POWER_GATE_RAM_BLOCK_0_ACK,
    POWER_MANAGER_RAM_0_SWITCH,
    POWER_MANAGER_RAM_0_WAIT_ACK_SWITCH_ON,
    POWER_MANAGER_RAM_0_ISO,
    POWER_MANAGER_RAM_0_RETENTIVE,
    POWER_MANAGER_RAM_1_CLK_GATE,
    POWER_MANAGER_POWER_GATE_RAM_BLOCK_1_ACK,
    POWER_MANAGER_RAM_1_SWITCH,
    POWER_MANAGER_RAM_1_WAIT_ACK_SWITCH_ON,
    POWER_MANAGER_RAM_1_ISO,
    POWER_MANAGER_RAM_1_RETENTIVE,
    POWER_MANAGER_RAM_2_CLK_GATE,
    POWER_MANAGER_POWER_GATE_RAM_BLOCK_2_ACK,
    POWER_MANAGER_RAM_2_SWITCH,
    POWER_MANAGER_RAM_2_WAIT_ACK_SWITCH_ON,
    POWER_MANAGER_RAM_2_ISO,
    POWER_MANAGER_RAM_2_RETENTIVE,
    POWER_MANAGER_RAM_3_CLK_GATE,
    POWER_MANAGER_POWER_GATE_RAM_BLOCK_3_ACK,
    POWER_MANAGER_RAM_3_SWITCH,
    POWER_MANAGER_RAM_3_WAIT_ACK_SWITCH_ON,
    POWER_MANAGER_RAM_3_ISO,
    POWER_MANAGER_RAM_3_RETENTIVE,
    POWER_MANAGER_MONITOR_POWER_GATE_CORE,
    POWER_MANAGER_MONITOR_POWER_GATE_PERIPH,
    POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_0,
    POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_1,
    POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_2,
    POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_3,
    POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_OFF,
    POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_ON,
    POWER_MANAGER_MASTER_CPU_FORCE_RESET_ASSERT,
    POWER_MANAGER_MASTER_CPU_FORCE_RESET_DEASSERT,
    POWER_MANAGER_MASTER_CPU_FORCE_ISO_OFF,
    POWER_MANAGER_MASTER_CPU_FORCE_ISO_ON
  } power_manager_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] POWER_MANAGER_PERMIT[61] = '{
      4'b0001,  // index[ 0] POWER_MANAGER_WAKEUP_STATE
      4'b1111,  // index[ 1] POWER_MANAGER_RESTORE_ADDRESS
      4'b1111,  // index[ 2] POWER_MANAGER_GLOBAL_POINTER
      4'b1111,  // index[ 3] POWER_MANAGER_EN_WAIT_FOR_INTR
      4'b1111,  // index[ 4] POWER_MANAGER_INTR_STATE
      4'b0001,  // index[ 5] POWER_MANAGER_POWER_GATE_CORE
      4'b0001,  // index[ 6] POWER_MANAGER_POWER_GATE_CORE_ACK
      4'b1111,  // index[ 7] POWER_MANAGER_CPU_RESET_ASSERT_COUNTER
      4'b1111,  // index[ 8] POWER_MANAGER_CPU_RESET_DEASSERT_COUNTER
      4'b1111,  // index[ 9] POWER_MANAGER_CPU_SWITCH_OFF_COUNTER
      4'b1111,  // index[10] POWER_MANAGER_CPU_SWITCH_ON_COUNTER
      4'b0001,  // index[11] POWER_MANAGER_CPU_WAIT_ACK_SWITCH_ON_COUNTER
      4'b1111,  // index[12] POWER_MANAGER_CPU_ISO_OFF_COUNTER
      4'b1111,  // index[13] POWER_MANAGER_CPU_ISO_ON_COUNTER
      4'b0001,  // index[14] POWER_MANAGER_CPU_COUNTERS_STOP
      4'b0001,  // index[15] POWER_MANAGER_POWER_GATE_PERIPH_ACK
      4'b0001,  // index[16] POWER_MANAGER_PERIPH_RESET
      4'b0001,  // index[17] POWER_MANAGER_PERIPH_SWITCH
      4'b0001,  // index[18] POWER_MANAGER_PERIPH_WAIT_ACK_SWITCH_ON
      4'b0001,  // index[19] POWER_MANAGER_PERIPH_ISO
      4'b0001,  // index[20] POWER_MANAGER_PERIPH_CLK_GATE
      4'b0001,  // index[21] POWER_MANAGER_DMA_CH0_CLK_GATE
      4'b0001,  // index[22] POWER_MANAGER_DMA_CH1_CLK_GATE
      4'b0001,  // index[23] POWER_MANAGER_DMA_CH2_CLK_GATE
      4'b0001,  // index[24] POWER_MANAGER_DMA_CH3_CLK_GATE
      4'b0001,  // index[25] POWER_MANAGER_RAM_0_CLK_GATE
      4'b0001,  // index[26] POWER_MANAGER_POWER_GATE_RAM_BLOCK_0_ACK
      4'b0001,  // index[27] POWER_MANAGER_RAM_0_SWITCH
      4'b0001,  // index[28] POWER_MANAGER_RAM_0_WAIT_ACK_SWITCH_ON
      4'b0001,  // index[29] POWER_MANAGER_RAM_0_ISO
      4'b0001,  // index[30] POWER_MANAGER_RAM_0_RETENTIVE
      4'b0001,  // index[31] POWER_MANAGER_RAM_1_CLK_GATE
      4'b0001,  // index[32] POWER_MANAGER_POWER_GATE_RAM_BLOCK_1_ACK
      4'b0001,  // index[33] POWER_MANAGER_RAM_1_SWITCH
      4'b0001,  // index[34] POWER_MANAGER_RAM_1_WAIT_ACK_SWITCH_ON
      4'b0001,  // index[35] POWER_MANAGER_RAM_1_ISO
      4'b0001,  // index[36] POWER_MANAGER_RAM_1_RETENTIVE
      4'b0001,  // index[37] POWER_MANAGER_RAM_2_CLK_GATE
      4'b0001,  // index[38] POWER_MANAGER_POWER_GATE_RAM_BLOCK_2_ACK
      4'b0001,  // index[39] POWER_MANAGER_RAM_2_SWITCH
      4'b0001,  // index[40] POWER_MANAGER_RAM_2_WAIT_ACK_SWITCH_ON
      4'b0001,  // index[41] POWER_MANAGER_RAM_2_ISO
      4'b0001,  // index[42] POWER_MANAGER_RAM_2_RETENTIVE
      4'b0001,  // index[43] POWER_MANAGER_RAM_3_CLK_GATE
      4'b0001,  // index[44] POWER_MANAGER_POWER_GATE_RAM_BLOCK_3_ACK
      4'b0001,  // index[45] POWER_MANAGER_RAM_3_SWITCH
      4'b0001,  // index[46] POWER_MANAGER_RAM_3_WAIT_ACK_SWITCH_ON
      4'b0001,  // index[47] POWER_MANAGER_RAM_3_ISO
      4'b0001,  // index[48] POWER_MANAGER_RAM_3_RETENTIVE
      4'b0001,  // index[49] POWER_MANAGER_MONITOR_POWER_GATE_CORE
      4'b0001,  // index[50] POWER_MANAGER_MONITOR_POWER_GATE_PERIPH
      4'b0001,  // index[51] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_0
      4'b0001,  // index[52] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_1
      4'b0001,  // index[53] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_2
      4'b0001,  // index[54] POWER_MANAGER_MONITOR_POWER_GATE_RAM_BLOCK_3
      4'b0001,  // index[55] POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_OFF
      4'b0001,  // index[56] POWER_MANAGER_MASTER_CPU_FORCE_SWITCH_ON
      4'b0001,  // index[57] POWER_MANAGER_MASTER_CPU_FORCE_RESET_ASSERT
      4'b0001,  // index[58] POWER_MANAGER_MASTER_CPU_FORCE_RESET_DEASSERT
      4'b0001,  // index[59] POWER_MANAGER_MASTER_CPU_FORCE_ISO_OFF
      4'b0001  // index[60] POWER_MANAGER_MASTER_CPU_FORCE_ISO_ON
  };

endpackage

